import {useState} from 'react';
import {useNewsReader} from '../use-news-reader.ts';
import type {Article,ArticleDetail,Brief,ReaderSnapshot} from '../news-reader-contract.ts';
import {materials} from './data.ts';
export const readerArticleId='aaccee00112233445566778899001122',readerStoryId='c'.repeat(64);
const categories=[['ai-models','模型'],['ai-products','产品'],['industry','行业'],['paper','论文'],['tip','教程'],['opinion','观点']].map(([key,label])=>({key,label,section:label,guide:'明确标记的 UI 虚构类别'}));
export const readerArticle:Article={id:readerArticleId,material:{...materials[0],id:readerArticleId,title:'Explicit UI fixture',publishedAt:'2026-10-05T02:00:00Z'},titleZh:'UI虚构示例：产品开放公开预览，读取免费，导出仍消耗额度',summaryZh:'这款虚构产品开放公开预览。读取功能免费，导出仍需要消耗额度，两项操作分别保留适用条件。此示例只展示共用 UI 组件和布局，不代表真实新闻。',reason:'公开范围与收费条件分别说明，便于确认适用对象。',category:'ai-products',tags:['产品更新'],subjects:[],scope:'single',fact:null,scoreFirst:80,scoreSecond:90,score:85,tier:'T1',selected:true,addsValue:true,selectionReason:'',occurrenceId:readerStoryId,storyId:readerStoryId,originalBody:'## 公开范围\n\n这段正文是 UI 虚构资料。页面沿用统一亮暗主题和通用控件，使用右侧容器全部宽度。\n\n## 价格与限制\n\n读取免费，导出消耗额度。两项操作的条件分别展示。\n\n- 免费范围仅包含读取。\n- 导出仍需消耗额度。\n\n```js\nconst count = 2;\n```\n\n| 操作 | 条件 |\n| --- | --- |\n| 读取 | 免费 |\n| 导出 | 消耗额度 |',translatedBody:null,bodyKind:'feed',bodyError:null,displayBody:true,status:'ready',processedAt:'2026-10-05T03:00:00Z',configRevision:1,upstream:'explicit-ui-fixture'};
export function usePreviewReader(state:string){
 const baseline=useNewsReader(null,false),[items,setItems]=useState<Article[]>([readerArticle,{...readerArticle,id:'bb'.repeat(16),titleZh:'UI虚构示例：后续报道说明开放范围',selected:false,material:{...readerArticle.material,sourceName:'第二测试信源'}}]);
 const [tab,setTab]=useState<typeof baseline.tab>(state==='hot'?'hot':state==='daily'?'daily':state==='bookmarks'?'bookmarks':state==='featured'?'featured':'all'),[category,setCategory]=useState(''),[query,setQuery]=useState(''),[limit,setLimit]=useState(100),[editionId,setEditionId]=useState('');
 const brief=(a:Article):Brief=>({id:a.id,titleZh:a.titleZh,summaryZh:a.summaryZh,sourceName:a.material.sourceName,publishedAt:a.material.publishedAt,storyId:a.storyId,occurrenceId:a.occurrenceId,url:a.material.url});
 const filtered=state==='empty'||state==='filtered'?[]:items.filter(a=>(tab!=='featured'||a.selected)&&(tab!=='bookmarks'||a.bookmarked)&&(!category||a.category===category||a.tags.includes(category))&&(!query||a.titleZh.includes(query)));
 const snapshot:ReaderSnapshot={items:filtered,total:filtered.length,taxonomy:{categories,topicTags:['产品更新']},upstream:'explicit-ui-fixture',stories:[{id:readerStoryId,title:readerArticle.titleZh,digest:{title:'UI虚构事件概览',digest:'示例事件开放预览，后续报道补充适用条件。此文字用于展示排版。'},heat:1.7,sources:2,latestAt:readerArticle.material.publishedAt,articles:items.map(brief)}],editions:[{id:'explicit-ui-edition',kind:'daily',date:'2026-10-05',windowStart:'2026-10-04T00:00:00Z',windowEnd:'2026-10-05T00:00:00Z',generatedAt:'2026-10-05T00:01:00Z',overview:'UI虚构日报：本期展示公开范围和收费条件。',sections:{},main:items.map(brief),flashes:[],gaps:state==='incomplete'?['测试信源：本窗口无成功采集']:[],upstream:'explicit-ui-fixture'}]};
 const article={...readerArticle,titleZh:state==='long'?readerArticle.titleZh.repeat(3):readerArticle.titleZh,originalBody:state==='long'?readerArticle.originalBody+'\n\n'+('长文本 UI 示例，核对断行和容器宽度。'.repeat(140)):readerArticle.originalBody};
 const detail:ArticleDetail={article,bookmarked:state==='bookmarks',position:0,related:[],steps:[]};
 return {reader:{...baseline,snapshot,tab,setTab,category,setCategory,query,setQuery,limit,setLimit,editionId,setEditionId,loading:state==='loading',error:state==='error'?'UI示例读取失败，已保留内容':'',bookmark:async(id:string,value:boolean)=>setItems(before=>before.map(a=>a.id===id?{...a,bookmarked:value}:a)),refresh:async()=>{}},detail};
}
