const fs=require('node:fs'),path=require('node:path');
const {browserRuntime}=require('./support/browser.cjs');const {validationRun}=require('./support/validation-run.cjs');const{installNewsFixture}=require('./support/news-fixture.cjs');
(async()=>{const{out,hashes}=validationRun('news-ui-fixtures',['app/src','app/src-tauri/src','scripts','tests/verify-news-ui.cjs','tests/support/news-fixture.cjs']);const report={mode:'explicit news IPC/model replay, browser UI validation; not real inference',before:hashes(),checks:[],errors:[]};const{chromium,executablePath}=browserRuntime();const browser=await chromium.launch({executablePath,headless:true});let page;
 const check=(name,ok,detail)=>{report.checks.push({name,ok,detail});if(!ok)throw Error(name);};
 try{const context=await browser.newContext({viewport:{width:1440,height:900}});page=await context.newPage();page.on('pageerror',e=>report.errors.push(e.message));await page.addInitScript(installNewsFixture);await page.goto((process.env.AZCINE_NEWS_WEB_URL||'http://127.0.0.1:1421')+'/#news');await page.locator('.news-entry').first().waitFor();
 check('默认精选且仅一套三个领域入口',await page.getByRole('button',{name:'精选',exact:true}).getAttribute('aria-pressed')==='true'&&await page.locator('.news-domain-tabs').count()===1&&await page.locator('.news-domain-tabs button').count()===4);
 await page.getByRole('button',{name:'精选',exact:true}).focus();await page.keyboard.press('Tab');check('键盘顺序与可见焦点',await page.evaluate(()=>{const e=document.activeElement,s=getComputedStyle(e);return e.textContent==='全部动态'&&e.matches(':focus-visible')&&s.outlineStyle!=='none'&&parseFloat(s.outlineWidth)>=2;}));await page.keyboard.press('Enter');check('键盘Enter切换阅读页签',await page.getByRole('button',{name:'全部动态',exact:true}).getAttribute('aria-pressed')==='true');
 await page.getByRole('button',{name:'全部动态',exact:true}).click();check('低分资讯仍在全部动态',await page.locator('.news-entry').count()===15);await page.getByRole('button',{name:'热点',exact:true}).click();check('热点按事件展示两个来源',await page.locator('.news-entry').count()===15);
 await page.getByRole('button',{name:'大模型前沿',exact:true}).click();await page.locator('.workspace-scroll').evaluate(e=>e.scrollTop=250);const scroll=await page.locator('.workspace-scroll').evaluate(e=>e.scrollTop);await page.locator('.news-entry-title a').first().click();await page.locator('.news-article').waitFor();check('详情显示导读、事实和许可边界',await page.locator('#news-guide').isVisible()&&await page.locator('#news-facts').count()===1&&(await page.locator('#news-body').innerText()).includes('未取得许可正文'));
 await page.getByRole('button',{name:'订阅原文',exact:true}).click();check('原文HTML严格按文本显示',await page.locator('.news-original img').count()===0&&await page.evaluate(()=>window.fixtureInjected)!==true);
 await page.getByRole('link',{name:'← 返回资讯（保留筛选）',exact:true}).click();await page.locator('.news-entry').first().waitFor();check('返回列表保留领域与滚动',await page.getByRole('button',{name:'大模型前沿',exact:true}).getAttribute('aria-pressed')==='true'&&Math.abs((await page.locator('.workspace-scroll').evaluate(e=>e.scrollTop))-scroll)<2);
 await page.getByRole('button',{name:'日报',exact:true}).click();await page.locator('.news-edition-document pre').waitFor();check('日报不受领域筛选影响且完整窗口可读',(await page.locator('.news-edition-document pre').innerText()).includes('事件 14')&&(await page.locator('.news-edition-document pre').innerText()).includes('完整窗口'));
 await page.getByRole('button',{name:'导出A4 PDF',exact:true}).click();await page.getByText('已取消导出，刊期保留。',{exact:true}).waitFor();check('导出取消不报成功',await page.locator('.news-edition-document pre').isVisible());
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>Promise.reject(Error('explicit clipboard denied'))}}));await page.getByRole('button',{name:'复制整期',exact:true}).click();await page.locator('.news-copy-text').waitFor();check('复制受限保留完整手选文本',(await page.locator('.news-copy-text').inputValue())===(await page.locator('.news-edition-document pre').innerText()));

 // Explicit late IPC and clipboard replies must remain bound to their edition.
 const editions=await page.evaluate(()=>{const f=window.newsFixture,old=f.editorial.editions[0],next={...structuredClone(old),id:'aabbccdd-1111-2222-3333-000000000002',version:2};f.editorial.editions.unshift(next);f.emit('news-editorial-changed');return{old:old.id,next:next.id};});
 const selection=page.locator('.news-edition-select select');await selection.selectOption(editions.old);
 await page.evaluate(id=>{const original=window.__TAURI_INTERNALS__.invoke;window.__copyOriginalInvoke=original;window.__TAURI_INTERNALS__.invoke=async(command,args)=>{const result=await original(command,args);if(command==='news_edition_text'&&args.id===id)return new Promise(resolve=>window.__releaseEditionText=()=>resolve(result));return result;};},editions.old);
 await page.getByRole('button',{name:'复制整期',exact:true}).click();await page.waitForFunction(()=>!!window.__releaseEditionText);await selection.selectOption(editions.next);
 await page.evaluate(()=>{window.__TAURI_INTERNALS__.invoke=window.__copyOriginalInvoke;window.__releaseEditionText();});await page.getByRole('button',{name:'复制整期',exact:true}).waitFor({state:'visible'});await page.waitForFunction(()=>!document.querySelector('.form-actions button')?.disabled);
 check('复制旧刊IPC延迟时切新刊不展示旧刊手选文本',await page.locator('.news-copy-text').count()===0);
 await selection.selectOption(editions.old);check('选回原刊仍能手选刚才的完整内容',await page.locator('.news-copy-text').inputValue()===(await page.locator('.news-edition-document pre').innerText()));
 await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:()=>new Promise((_resolve,reject)=>window.__releaseClipboard=()=>reject(Error('explicit delayed clipboard denial')))}}));
 await page.getByRole('button',{name:'复制整期',exact:true}).click();await page.waitForFunction(()=>!!window.__releaseClipboard);await selection.selectOption(editions.next);await page.evaluate(()=>window.__releaseClipboard());await page.waitForFunction(()=>!document.querySelector('.form-actions button')?.disabled);
 check('剪贴板延迟切刊不串版且反馈明确第1版',await page.locator('.news-copy-text').count()===0&&(await page.locator('.news-page').innerText()).includes('第1版'));
 await page.evaluate(()=>window.newsFixture.editorial.editions.pop());
 await page.evaluate(()=>location.hash='settings/news/sources/rss-fixture-one');await page.getByLabel('名称',{exact:true}).waitFor();await page.getByLabel('名称',{exact:true}).fill('保存请求中的名称');await page.evaluate(()=>window.newsFixture.holdSource=true);await page.getByRole('button',{name:'保存配置',exact:true}).click();await page.waitForFunction(()=>!!window.newsFixture.sourcePending);await page.getByLabel('名称',{exact:true}).fill('较新的手动名称');await page.locator('nav a[href="#today"]').click();await page.getByRole('button',{name:/切换.*色/}).click();await page.evaluate(()=>{const f=window.newsFixture;f.sources[0]={...f.sources[0],revision:3,config:{...f.sources[0].config,name:'正式配置三'}};f.emit('news-progress',{sources:f.sources,runs:[]});f.resolveSource();});await page.evaluate(()=>location.hash='settings/news/sources/rss-fixture-one');await page.getByLabel('名称',{exact:true}).waitFor();check('延迟保存回执、较新快照、路由与主题均不覆盖后续手改',await page.getByLabel('名称',{exact:true}).inputValue()==='较新的手动名称'&&(await page.locator('.news-source-editor').innerText()).includes('v3'));
 await page.evaluate(()=>location.hash='settings/news/rules');const rule=()=>page.getByRole('textbox',{name:'大模型前沿范围与推荐规则',exact:true});await rule().waitFor();await rule().fill('保存时的规则');await page.evaluate(()=>window.newsFixture.holdPreferences=true);await page.getByRole('button',{name:'保存资讯配置',exact:true}).click();await page.waitForFunction(()=>!!window.newsFixture.preferencesPending);await rule().fill('较新的规则草稿');await page.locator('nav a[href="#news"]').click();await page.getByRole('button',{name:/切换.*色/}).click();await page.evaluate(()=>{const f=window.newsFixture;f.editorial.preferences={config:structuredClone(f.editorial.preferences.config),revision:3};f.emit('news-editorial-changed');});await page.waitForFunction(()=>window.newsFixture.calls.filter(c=>c.command==='news_editorial_snapshot').length>=2);await page.evaluate(()=>window.newsFixture.resolvePreferences());await page.evaluate(()=>location.hash='settings/news/rules');await rule().waitFor();check('规则保存旧回执不覆盖草稿或倒退版本',await rule().inputValue()==='较新的规则草稿'&&(await page.locator('.news-rules-form').innerText()).includes('领域与筛选'));
 await page.evaluate(()=>location.hash='news');await page.getByRole('button',{name:'精选',exact:true}).click();await page.getByRole('button',{name:'整理待处理资料',exact:true}).click();await page.getByText('明确回放：模型失败，材料和已完成批次保留。',{exact:true}).first().waitFor();check('模型失败保留旧刊与原事件',await page.locator('.news-entry').count()>0&&await page.evaluate(()=>window.newsFixture.editorial.editions.length===1));
 for(const theme of ['light','dark'])for(const size of [[1440,900],[1280,800],[1024,768]]){await page.setViewportSize({width:size[0],height:size[1]});await page.evaluate(t=>document.documentElement.dataset.theme=t,theme);for(const [route,name]of [['news','reading'],['news/events/'+('0'.repeat(64)),'article'],['settings/news','sources'],['settings/news/rules','rules']]){await page.evaluate(h=>location.hash=h,route);await page.waitForTimeout(80);await page.locator('.workspace-scroll').evaluate(e=>e.scrollTo(0,0));const measured=await page.evaluate(()=>({viewport:innerWidth,document:document.documentElement.scrollWidth,scroll:document.querySelector('.workspace-scroll').clientWidth,content:document.querySelector('.workspace-scroll').scrollWidth}));check(`无横溢出 ${theme} ${size.join('x')} ${name}`,measured.document<=measured.viewport+1&&measured.content<=measured.scroll+1,measured);await page.screenshot({path:path.join(out,`${name}-${theme}-${size.join('x')}.png`)});}}
 report.after=hashes();check('源码稳定',JSON.stringify(report.before)===JSON.stringify(report.after));check('无浏览器异常',report.errors.length===0);
 }catch(e){report.failure=String(e);process.exitCode=1;if(page){await page.screenshot({path:path.join(out,'failure.png')}).catch(()=>{});report.failureState=await page.evaluate(()=>({hash:location.hash,body:document.body.innerText})).catch(()=>null);}}finally{await browser.close();fs.writeFileSync(path.join(out,'report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({out,checks:report.checks.length,failure:report.failure}));}})().catch(e=>{console.error(e);process.exitCode=1;});
