fn main() {
    tauri_build::try_build(tauri_build::Attributes::new().app_manifest(
        tauri_build::AppManifest::new().commands(&[
            "dev_environment_inspect", "dev_environment_status", "dev_environment_export", "dev_environment_cancel", "dev_environment_open",
            "task_panel_launch", "task_panel_worktree", "task_panel_workspace_forget",
        "task_panel_workspace_open", "task_panel_workspaces", "task_panel_agent_access", "task_panel_agent_accesses", "task_panel_agent_revoke", "task_panel_validation_identity", "task_panel_list", "task_panel_mutate", "task_panel_graph", "task_panel_changes", "task_panel_context", "task_panel_context_get", "task_panel_imports", "task_panel_import_preview", "task_panel_import_apply", "task_panel_herdr_config", "task_panel_herdr_config_save", "task_panel_herdr_status", "task_panel_herdr_sessions", "task_panel_bind", "task_panel_focus", "task_panel_dispatch", "task_panel_execution_action", "task_panel_create_execution", "task_panel_result", "task_panel_check", "task_panel_accept", "task_panel_index", "task_panel_recovery", "task_panel_goal", "task_panel_analysis",
            "check_desktop", "storage_workspace", "select_data_root", "create_todo", "complete_todo", "set_todo_deleted", "pick_data_root", "open_data_root", "list_projects", "save_project", "project_request", "project_catalog", "set_project_deleted", "project_deletion_request",
            "news_snapshot", "news_materials", "save_news_source", "news_source_request", "preview_news_source", "collect_news", "retry_news_run", "open_news_url", "cancel_news_capture", "news_reader_snapshot", "news_article_detail", "news_reader_mark", "news_reader_steps", "news_reader_period", "news_reader_image", "news_reader_export", "news_reader_step_detail", "news_editorial_snapshot", "news_pending_materials", "news_dismiss_pending", "news_reset_preview", "news_reset_data", "news_processing_snapshot", "news_task_detail", "save_news_preferences", "news_preference_request", "organize_news", "retry_news_editorial", "cancel_news_editorial", "analyze_news_event", "news_edition_text", "export_news_edition",
            "list_ideas", "idea_request", "save_idea", "set_idea_deleted", "convert_idea",
            "bookkeeping_list", "bookkeeping_mutate", "bookkeeping_request", "bookkeeping_add_receipt", "bookkeeping_open_receipt", "bookkeeping_export", "bookkeeping_exchange_rate",
            "agent_context_catalog", "agent_conversation", "agent_view_conversation", "agent_bind", "agent_delete_conversation", "agent_remember", "agent_send", "agent_drafts", "agent_revalidate_draft", "agent_apply_draft", "agent_discard_draft", "agent_attach_file", "agent_attachment_preview", "agent_jobs", "agent_submit_job", "agent_cancel_job", "pi_runtime_summary", "pi_save_runtime", "pi_respond_ui", "pi_thinking", "pi_stats", "pi_snapshot", "pi_connect", "pi_disconnect", "pi_send", "pi_stop", "pi_sessions", "pi_resources", "pi_save_resource", "pi_new_session", "pi_switch_session", "pi_name_session", "pi_select_model", "pi_save_model", "pi_providers", "pi_save_provider", "pi_fetch_models",
            "model_ranking_workspace", "model_ranking_update", "model_ranking_attempt", "model_ranking_open_source",
        ]),
    )).expect("build app command permissions");
}
