/* 虚构新闻素材：仅演示新闻阅读与来源追溯，不指代真实机构或已发生事件。 */
window.AZ_NEWS = [
  {id:'e2',kind:'教程',field:'大模型前沿',firstHand:true,date:'2026-10-01',time:'09:05',title:'工具失败后如何恢复：行舟团队公布 Agent 长任务评测方案',originalTitle:'Recovering Long-Running Agents After Tool Failures',summary:'行舟研究组公布一套长任务恢复测试，将工具超时、空结果和进程中断分开评估。方案保留每一步的输入、返回与重试记录，并要求恢复后的任务从中断处继续，而不是重新运行整个流程。',reason:'给出了错误注入步骤与记录字段，适合检查自己的 Agent 工作流是否真的能恢复，而不只是偶尔跑通。',tags:['Agent','评测','工程实践'],sources:[{name:'行舟研究组',channel:'技术博客 · 一手',published:'2026-10-01 08:40',url:'https://example.com/agent-recovery',full:true},{name:'工具观察室',channel:'复现笔记',published:'2026-10-01 09:00',url:'https://example.com/recovery-notes',full:false}],updates:[{time:'08:40',text:'发布测试步骤与错误场景。'},{time:'09:00',text:'补充一份独立复现笔记，已并入同一事件。'}],sections:[
    {id:'overview',title:'简而言之',paragraphs:['这套方案不比较模型能回答多少道题，而是检查一项真实任务被打断之后，系统是否知道自己已经做过什么、还缺什么。一次运行的记录包括任务输入、工具参数、工具返回、错误原因和人工确认点。'],bullets:['将超时、空返回与进程中断作为三种不同故障，不统一包装成“执行失败”。','恢复时优先使用已有结果，避免重复写文件或重复提交请求。','把“继续执行”与“从头重跑”分开计数，保留每次恢复的过程记录。']},
    {id:'scenarios',title:'先构造三种失败场景',paragraphs:['第一种场景让读取工具超过等待时间。系统应当留下超时位置，而不是将空值当成有效内容。第二种场景让工具正常返回但没有结果，用来检查 Agent 是否会识别信息不足。','第三种场景在任务进行到一半时结束进程。重新启动后，测试者需要比较已有输出和运行记录，确认同一步骤没有被重复执行。错误注入位置应固定，方便横向比较不同运行。']},
    {id:'steps',title:'怎样接入自己的工作流',paragraphs:['先挑一项输入清楚、结果容易检查的短任务，记录无故障时的正常过程。然后在相同输入下逐一加入故障，只改变一个条件，不同时更换模型、工具和任务资料。','每次恢复后都检查中间文件、工具调用次数和最终结果。保存了日志并不等于能正确恢复：如果所有步骤被重新执行，或者旧错误被覆盖，这次运行仍然应该单独标记。']},
    {id:'limits',title:'这份测试还没有回答什么',paragraphs:['示例方案关注单个任务的恢复，不覆盖多设备同步、服务端持久队列以及有副作用的外部接口。包含支付、发布、删除等动作的流程，需要额外的授权与幂等策略，不能因为一次测试通过就直接放开自动执行。']}
  ]},
  {id:'e1',kind:'论文',field:'AI 视频、图片 / CG 应用',firstHand:true,date:'2026-10-01',time:'08:42',title:'多镜头一致性测试集公开：帧序实验室提供参考、参数与失败样例',originalTitle:'A Repeatable Test Set for Multi-shot Consistency',summary:'帧序实验室发布一组覆盖景别、视角和光照变化的多镜头测试样例。与只展示单张最好结果不同，材料同时保留固定参考、生成设置和失败画面，方便比较同一角色在连续镜头中的身份与服装稳定性。',reason:'提供可复查的输入与失败条件，能够直接转成自己的小规模测试；样例效果仍需用项目素材复测。',tags:['图像生成','角色一致性','CG 工作流'],sources:[{name:'帧序实验室',channel:'研究记录 · 一手',published:'2026-10-01 08:20',url:'https://example.com/sequence-test',full:true},{name:'镜头手记',channel:'测试观察',published:'2026-10-01 08:32',url:'https://example.com/sequence-notes',full:false},{name:'影像工具周刊',channel:'资料汇总',published:'2026-10-01 08:40',url:'https://example.com/sequence-roundup',full:false}],updates:[{time:'08:20',text:'发布固定参考与基础测试组。'},{time:'08:32',text:'新增侧脸与背光条件的失败样例。'}],sections:[
    {id:'overview',title:'这次公开了哪些材料',paragraphs:['样例围绕同一角色展开，分别改变景别、机位和光照。资料包把参考图版本、镜头描述、参数与输出放在同一条记录里，保留每轮生成结果，而不是只挑选一张成功画面。'],bullets:['同一参考下分别测试近景、中景和远景。','每次只改变一个变量，保留失败画面与对应条件。','把角色身份、服装细节和画面风格分开检查。']},
    {id:'method',title:'从单张效果转向连续镜头',paragraphs:['单张图像看起来正确，并不意味着它适合剪进一组镜头。面部比例、衣领结构或光线方向的细小变化，在连续播放时会变得明显。测试因此将单张质量与序列稳定性分开记录。','对照时先固定角色参考和镜头描述，再依次改变角度或光照。不要同时修改多个参数，否则很难知道哪一项改变带来了改善。']},
    {id:'failures',title:'失败样例为什么值得留下',paragraphs:['示例记录中，一些问题只在侧脸与强背光条件下出现。如果只保存成功结果，后续换镜头时仍会重复踩到同样的限制。失败样例包含输入、结果和简短观察，方便后续回查。']},
    {id:'limits',title:'用于制作前仍需复测',paragraphs:['公开记录不是项目交付保证。不同角色、参考图片质量与输出尺寸都可能改变结果，正式使用前仍需要自己的对照测试。这篇虚构样稿只演示如何阅读材料，不构成真实模型效果结论。']}
  ]},
  {id:'e3',kind:'行业',field:'AI 行业动态',firstHand:true,date:'2026-10-01',time:'08:10',title:'雾桥工作室公开 AI 制作归档模板，将引用、实验与人工确认分开记录',originalTitle:'Keeping Sources, Experiments and Decisions Separate',summary:'雾桥工作室展示一套面向 AI 辅助制作的项目归档方法：原始材料只保存出处，实验记录保留步骤与参数，最终采用的方案另外记录确认人和版本。模板将“看到的结果”与“自己验证过的结果”分开，减少转述中的信息误用。',reason:'有具体记录结构，而不只是泛泛谈流程；适合参考研究与项目资料的组织方式。',tags:['行业实践','资料归档','制作流程'],sources:[{name:'雾桥工作室',channel:'工作室笔记 · 一手',published:'2026-10-01 07:50',url:'https://example.com/archive-template',full:true}],updates:[],sections:[
    {id:'overview',title:'三种记录，不混在一起',paragraphs:['原始材料回答“信息从哪里来”，实验记录回答“自己做了什么”，确认记录回答“最后采用哪一版”。模板用三种独立记录组织同一项目，彼此引用，而不是复制到一篇越来越长的笔记里。'],bullets:['引用保留原始标题、时间与链接。','实验保留步骤、参数与成功或失败的输出。','正式方案记录采用版本及人工确认。']},
    {id:'workflow',title:'一次制作变更怎样留下来',paragraphs:['收到新的制作要求后，先把来源附在项目上，再列出相对上一版的差异。需要测试的部分进入实验记录，确认后的变更才写入正式交付表。来源不清楚的日期或编号保持待核对，不凭上下文补齐。']},
    {id:'limits',title:'案例方法不等于行业统计',paragraphs:['这份材料展示的是一套记录方式，没有给出行业采用率或效率提升数据。可以借鉴它的结构，但不能将一个工作室的做法写成已经被广泛证明的趋势。']}
  ]},
  {id:'e4',kind:'产品',field:'AI 视频、图片 / CG 应用',firstHand:true,date:'2026-09-30',time:'22:20',title:'映格素材工具新增序列对比视图，可同步查看相邻版本的画面变化',summary:'映格素材工具展示新的序列对比方式：两版画面共享帧位置，查看者可以逐帧切换并留下修改备注。演示重点放在版本回查与结果核对，而不是自动评价画面好坏。',reason:'与镜头版本核对直接相关，但本期只取得摘要，实际支持格式和性能仍需查看原始材料。',tags:['版本对比','制作工具'],sources:[{name:'映格工具日志',channel:'更新日志 · 一手',published:'2026-09-30 22:00',url:'https://example.com/version-compare',full:false}],updates:[],sections:[]},
  {id:'e5',kind:'模型',field:'大模型前沿',firstHand:false,date:'2026-09-30',time:'19:45',title:'长上下文不等于稳定执行：一份小规模评测记录工具使用中的信息遗漏',summary:'工具观察室对相同任务分别保留完整对话与压缩记录，比较模型在多步调用后是否仍能遵守最初约束。记录同时列出遗漏条件，没有将单次成功输出当成稳定能力。',reason:'测试条件与失败过程可追溯，适合关注长任务质量；样本规模有限，不能代替全面评测。',tags:['长上下文','模型评测'],sources:[{name:'工具观察室',channel:'评测笔记',published:'2026-09-30 19:30',url:'https://example.com/context-test',full:false}],updates:[],sections:[]},
  {id:'e6',kind:'观点',field:'AI 行业动态',firstHand:false,date:'2026-09-30',time:'17:30',title:'自动化交付的最后一步：为什么确认记录比一句“已经完成”更重要',summary:'一篇制作流程观察讨论了自动化结果怎样进入正式项目。作者建议把生成结果、人工检查和正式采用分开，避免团队成员误把待评估输出当成最终交付版本。',reason:'提出清楚的流程边界，可对照自己的交付方式；观点不等于事实或行业共识。',tags:['交付流程','观点'],sources:[{name:'制作旁注',channel:'专栏',published:'2026-09-30 17:00',url:'https://example.com/delivery-notes',full:false}],updates:[],sections:[]}
];
/* 首页使用同事件的短题 / 短摘要；保持 id、来源数量和判断一致，长文标题在资讯页展示。 */
window.AZ_V2.events.forEach(e=>{const n=window.AZ_NEWS.find(n=>n.id===e.id);Object.assign(e,{sources:n.sources.map(s=>s.name),fact:n.sections[0].paragraphs[0],analysis:n.reason});});
