// Explicit IPC replay, imported only by validation scripts. Never an application fallback.
function installNewsFixture(){
 const callbacks=new Map(),listeners=new Map();let callbackId=0,eventId=0;window.isTauri=true;
 const at='2026-10-04T00:00:00.000Z';const ids=n=>n.toString(16).padStart(32,'0');
 const config={model:null,domains:['frontiers','industry','visual'].map(domain=>({domain,enabled:true,rule:'明确回放：影视CG与AI coding相关性规则',minScore:50,dailyLimit:5})),featuredScore:75,overviewLimit:3,autoCollect:false,autoDaily:false,dailyTime:'09:00'};
 const sources=['rss-fixture-one','rss-fixture-two'].map((id,i)=>({config:{id,name:'明确回放来源 '+(i+1),feedUrl:'https://example.org/feed/'+i,identity:'media',domains:[],usage:'editorial',intervalMinutes:120,enabled:true},revision:1,createdAt:at,feedKind:'rss',lastAttemptAt:at,lastSuccessAt:at,lastStatus:'added',lastError:null}));
 const events=Array.from({length:15},(_,i)=>{const materials=Array.from({length:2},(_,j)=>({id:ids(i*2+j+1),sourceId:sources[j].config.id,sourceName:sources[j].config.name,sourceRevision:1,title:'原文标题 <img src=x onerror=window.fixtureInjected=true> '+i,url:'https://example.org/explicit/'+i+'/'+j+'?long='+('x'.repeat(200)),publishedAt:j?null:at,publishedRaw:null,discoveredAt:at,summary:'明确回放原文摘要，只用于测试，不是真实新闻。'+('中英文长文本 CG AI evidence '.repeat(20)),summaryTruncated:false}));return{id:i.toString(16).padStart(64,'0'),revision:1,draft:{eventKey:'explicit-event-'+i,materialIds:materials.map(m=>m.id),domain:['frontiers','industry','visual'][i%3],title:'明确回放 · 中文资讯事件 '+i+' '+(i===0?'长标题检查，来源事实与工作价值同时可读，所有内容仅用于界面验证':'光照、视频与模型工具的新进展'),summary:'显式模型回放，非真实推理。订阅事实有出处，分析和推荐保持独立。'+('长中文段落检查阅读舒适度。'.repeat(5)),facts:[{text:'明确测试的来源事实，未亲测。',materialIds:materials.map(m=>m.id)}],score:i<12?85:20,reason:'AI判断：可能改善影视CG流程；价值评分不代表可信概率。',tags:['影视CG','模型工具'],limitations:['仅根据订阅摘要，未取得正文许可。','多订阅来源并不等于独立核验。'],needsReview:false,hasNewFacts:true},materials,generatedAt:at,latestAt:at,configRevision:1,model:{provider:'explicit-fixture',id:'not-real-model'},promptVersion:1,featured:i<12,analysis:null};});
 const edition={id:'aabbccdd-1111-2222-3333-000000000001',date:'2026-10-04',version:1,generatedAt:at,windowStart:'2026-10-03T00:00:00.000Z',windowEnd:at,configRevision:1,overviewIds:events.slice(0,3).map(e=>e.id),events,incomplete:true,gaps:['明确回放来源三：抓取失败；本期覆盖不完整。']};
 window.newsFixture={sources,events,editorial:{preferences:{config,revision:1},events,editions:[edition],runs:[],pending:49,nextDailyAt:null},calls:[],holdSource:false,holdPreferences:false,sourcePending:null,preferencesPending:null,preferenceReceipts:new Map(),sourceReceipts:new Map(),copyDenied:false,emit(event,payload=null){for(const [id,l]of listeners)if(l.event===event)callbacks.get(l.handler)?.({id,event,payload:structuredClone(payload)});},resolveSource(){const p=this.sourcePending;const saved={...sources[0],config:p.input.source,revision:p.input.expectedRevision+1};this.sourceReceipts.set(p.input.requestId,saved);p.resolve(structuredClone(saved));this.sourcePending=null;},resolvePreferences(){const p=this.preferencesPending;const result={config:p.input.config,revision:p.input.expectedRevision+1};this.preferenceReceipts.set(p.input.requestId,result);p.resolve(structuredClone(result));this.preferencesPending=null;}};
 window.__TAURI_EVENT_PLUGIN_INTERNALS__={unregisterListener(_event,id){listeners.delete(id);}};
 window.__TAURI_INTERNALS__={transformCallback(callback){const id=++callbackId;callbacks.set(id,callback);return id;},unregisterCallback(id){callbacks.delete(id);},invoke:async(command,args)=>{
 const f=window.newsFixture;f.calls.push({command,args:structuredClone(args)});
 if(command==='plugin:event|listen'){const id=++eventId;listeners.set(id,args);return id;}if(command==='plugin:event|unlisten'){listeners.delete(args.eventId);return;}
 if(command==='storage_workspace')return{root:'X:/ExplicitNewsFixture',defaultRoot:'X:/ExplicitNewsFixture',todos:[]};if(command==='list_projects')return[];
 if(command==='pi_snapshot')return{generation:0,seq:0,connection:'disconnected',busy:false,stopping:false,sending:false,state:null,models:[],projection:{messages:[],partial:null,tools:[],steering:[],followUp:[],activity:'idle',outcome:'none',notice:null},recoveredQueue:[],error:null,notice:null,cwd:null,runtime:null,paths:null};
 if(command==='news_snapshot')return{sources:structuredClone(f.sources),runs:[]};if(command==='news_materials')return{items:[],total:0,page:0,pageSize:50};if(command==='news_editorial_snapshot')return structuredClone(f.editorial);
 if(command==='save_news_source'){if(f.holdSource)return new Promise((resolve,reject)=>f.sourcePending={resolve,reject,input:structuredClone(args.input)});const source=f.sources.find(s=>s.config.id===args.input.source.id);const result={...source,config:args.input.source,revision:source.revision+1};f.sources[f.sources.indexOf(source)]=result;f.sourceReceipts.set(args.input.requestId,result);return structuredClone(result);}
 if(command==='news_source_request')return structuredClone(f.sourceReceipts.get(args.requestId)??null);
 if(command==='save_news_preferences'){if(f.holdPreferences)return new Promise((resolve,reject)=>f.preferencesPending={resolve,reject,input:structuredClone(args.input)});const p={config:args.input.config,revision:args.input.expectedRevision+1};f.editorial.preferences=p;f.preferenceReceipts.set(args.input.requestId,p);return structuredClone(p);}
 if(command==='news_preference_request')return structuredClone(f.preferenceReceipts.get(args.requestId)??null);
 if(command==='news_edition_text')return 'AZCine 资讯日报 · 2026-10-04 · v1\n完整窗口：2026-10-03T00:00:00.000Z — 2026-10-04T00:00:00.000Z\n覆盖不完整\n'+events.map(e=>e.draft.title+'\n'+e.draft.summary+'\nAI判断：'+e.draft.reason+'\n'+e.materials.map(m=>m.url).join('\n')).join('\n\n');
 if(command==='export_news_edition')return null;if(command==='open_news_url')return;
 if(command==='organize_news'||command==='retry_news_editorial'){f.editorial.runs=[{id:args.requestId??args.runId,kind:args.kind??'organize',status:'failed',startedAt:at,finishedAt:at,windowStart:at,windowEnd:at,configRevision:1,config:structuredClone(config),total:49,processed:20,error:'明确回放：模型失败，材料和已完成批次保留。',scheduleDate:null}];throw{code:'news_ai_incomplete',message:'明确回放：模型失败，材料和已完成批次保留。'};}
 if(command==='cancel_news_editorial')return;if(command==='analyze_news_event')throw{code:'news_ai_incomplete',message:'明确回放：分析失败，事件保留。'};
 throw Error('Unexpected news fixture command: '+command);
 }};
}
module.exports={installNewsFixture};
