//! Fictitious local stores and adapters; never opens the normal development root.
use crate::{agent_store::*,storage::{Store,StorageError}};
use serde_json::{json,Value};
use rusqlite::{Transaction,params};
use std::{path::PathBuf,sync::Arc};
fn root()->PathBuf{let base=std::env::var_os("AZCINE_PI_CONFIG_TEST_ROOT").map(PathBuf::from).unwrap_or_else(||PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../artifacts/validation/agent-unit-tests"));std::fs::create_dir_all(&base).unwrap();tempfile::Builder::new().prefix("agent-").tempdir_in(base).unwrap().keep().join("data")}
struct Fixture;
impl ModuleProvider for Fixture{
 fn snapshot(&self,tx:&Transaction<'_>,source:&Source)->Result<ObjectContext,StorageError>{let (value,revision):(String,i64)=tx.query_row("SELECT value,revision FROM fixture_objects WHERE id=?",[source.object_id.as_ref().unwrap()],|r|Ok((r.get(0)?,r.get(1)?))).map_err(|_|StorageError::new("fixture_missing","明确测试对象不存在"))?;Ok(ObjectContext{source:source.clone(),revision,snapshot:json!({"value":value}),operations:vec!["rename".into()]})}
 fn validate(&self,_:&Transaction<'_>,op:&Operation,_:&ObjectContext)->Result<Value,StorageError>{if op.values["value"].as_str().is_none_or(|v|v.is_empty()){return Err(StorageError::new("fixture_invalid","明确测试缺值"));}Ok(json!({"objectId":op.object_id,"action":op.action}))}
 fn apply(&self,tx:&Transaction<'_>,op:&Operation,baseline:&ObjectContext)->Result<Value,StorageError>{let n=tx.execute("UPDATE fixture_objects SET value=?,revision=revision+1 WHERE id=? AND revision=?",params![op.values["value"].as_str(),op.object_id,baseline.revision]).map_err(|_|StorageError::new("fixture_write","明确测试写入失败"))?;if n!=1{return Err(StorageError::new("fixture_write","明确测试版本不一致"));}Ok(json!({"id":op.object_id,"value":op.values["value"]}))}
}
fn setup()->(Store,Providers,String){let mut store=Store::open(&root(),true).unwrap();store.db.execute_batch("CREATE TABLE fixture_objects(id TEXT PRIMARY KEY,value TEXT,revision INTEGER);INSERT INTO fixture_objects VALUES('one','旧值一',1),('two','旧值二',1);").unwrap();let mut providers=Providers::default();providers.0.insert("projects".into(),Arc::new(Fixture));let key=store.agent_bind(source("one"),false).unwrap()["conversationKey"].as_str().unwrap().to_owned();(store,providers,key)}
fn source(id:&str)->Source{Source{module:"projects".into(),page:"projects/test".into(),object_id:Some(id.into())}}
// Explicit fixture construction exercises transactional business validation;
// there is no assistant-reply parser in the production send path.
pub(crate) fn prepared_fixture(store:&mut Store,p:&Providers,key:&str,session:&str,mut context:Value,operations:Value)->Value{
 let id=crate::agent_store::id(store).unwrap();let input=context["inputId"].as_str().unwrap().to_owned();let tx=store.db.transaction().unwrap();
 let references=context["objects"].as_array().unwrap().clone();let objects=references.into_iter().map(|v|{let source:Source=serde_json::from_value(v["source"].clone()).unwrap();serde_json::to_value(p.module(&source.module).unwrap().snapshot(&tx,&source).unwrap()).unwrap()}).collect::<Vec<_>>();context["objects"]=json!(objects);
 let payload:DraftPayload=serde_json::from_value(json!({"version":1,"operations":operations,"decisions":[]})).unwrap();let(status,validation)=match validate_payload(&tx,&payload,&context,p){Ok(items)=>("review",json!({"items":items,"error":null})),Err(e)=>("blocked",json!({"items":[],"error":e.message}))};
 tx.execute("UPDATE agent_inputs SET context=? WHERE id=?",params![context.to_string(),input]).unwrap();
 tx.execute("INSERT INTO agent_drafts(id,conversation_id,input_id,message_key,payload,validation,status,created_at) VALUES(?,?,?,?,?,?,?,'explicit-fixture')",params![id,key,input,format!("fixture:{session}:{id}"),serde_json::to_string(&payload).unwrap(),validation.to_string(),status]).unwrap();tx.commit().unwrap();store.agent_drafts().unwrap().into_iter().find(|d|d["id"]==id).unwrap()
}
fn draft(store:&mut Store,p:&Providers,key:&str,operations:Value)->Value{let (id,context)=store.agent_prepare_input(key,"native-fixture",1,0,&[source("one"),source("two")],&[],p).unwrap();store.agent_input_status(&id,"accepted").unwrap();prepared_fixture(store,p,key,"native-fixture",context,operations)}
fn operations()->Value{json!([{"module":"projects","objectId":"one","action":"rename","values":{"value":"新值一"}},{"module":"projects","objectId":"two","action":"rename","values":{"value":"新值二"}}])}
fn value(store:&Store,id:&str)->String{store.db.query_row("SELECT value FROM fixture_objects WHERE id=?",[id],|r|r.get(0)).unwrap()}
#[test]fn source_binding_and_object_references_survive_reopen(){let(mut s,p,key)=setup();assert_eq!(s.agent_bind(source("one"),false).unwrap()["conversationKey"],key);s.db.execute("UPDATE fixture_objects SET value='手改',revision=2 WHERE id='one'",[]).unwrap();let(_,context)=s.agent_prepare_input(&key,"native-fixture",1,0,&[],&[],&p).unwrap();assert_eq!(context["objects"][0]["source"]["objectId"],"one");assert!(context["objects"][0].get("snapshot").is_none());let root=s.root.clone();drop(s);let mut reopened=Store::open(&root,false).unwrap();assert_eq!(reopened.agent_bind(source("one"),false).unwrap()["conversationKey"],key);let fresh=reopened.agent_bind(source("one"),true).unwrap();assert_ne!(fresh["conversationKey"],key);assert!(reopened.agent_conversation(&key).is_ok());}
#[test]fn prepared_draft_is_persisted_and_receipt_replay_does_not_write_twice(){let(mut s,p,key)=setup();let d=draft(&mut s,&p,&key,operations());assert_eq!(s.agent_drafts().unwrap().len(),1);assert_eq!(d["status"],"review");let receipt=s.agent_apply(d["id"].as_str().unwrap(),1,&p).unwrap();assert_eq!(receipt,s.agent_apply(d["id"].as_str().unwrap(),1,&p).unwrap());assert_eq!(value(&s,"one"),"新值一");assert_eq!(s.db.query_row("SELECT revision FROM fixture_objects WHERE id='one'",[],|r|r.get::<_,i64>(0)).unwrap(),2);}
#[test]fn changed_second_object_rejects_whole_batch_and_retains_conflict(){let(mut s,p,key)=setup();let d=draft(&mut s,&p,&key,operations());s.db.execute("UPDATE fixture_objects SET value='本人手改',revision=2 WHERE id='two'",[]).unwrap();assert_eq!(s.agent_apply(d["id"].as_str().unwrap(),1,&p).unwrap_err().code,"agent_baseline_conflict");assert_eq!(value(&s,"one"),"旧值一");assert_eq!(value(&s,"two"),"本人手改");assert_eq!(s.agent_drafts().unwrap()[0]["status"],"conflict");}
#[test]fn failure_during_second_write_rolls_back_first_write_and_receipt(){let(mut s,p,key)=setup();let d=draft(&mut s,&p,&key,operations());s.db.execute_batch("CREATE TRIGGER fixture_fail BEFORE UPDATE ON fixture_objects WHEN NEW.id='two' BEGIN SELECT RAISE(ABORT,'explicit fixture');END;").unwrap();assert!(s.agent_apply(d["id"].as_str().unwrap(),1,&p).is_err());assert_eq!(value(&s,"one"),"旧值一");assert_eq!(value(&s,"two"),"旧值二");let drafts=s.agent_drafts().unwrap();assert_eq!(drafts[0]["status"],"review");assert!(drafts[0]["receipt"].is_null());}
#[test]fn unknown_module_or_missing_baseline_is_blocked_before_formal_write(){let(mut s,p,key)=setup();let d=draft(&mut s,&p,&key,json!([{"module":"bookkeeping","objectId":"unknown","action":"rename","values":{"value":"猜值"}}]));assert_eq!(d["status"],"blocked");assert!(s.agent_apply(d["id"].as_str().unwrap(),1,&p).is_err());assert_eq!(value(&s,"one"),"旧值一");}
#[test]fn schema13_queue_upgrades_without_replacing_saved_input_or_identity(){let(mut s,_,_)=setup();let root=s.root.clone();s.db.execute("INSERT INTO agent_jobs(id,template,input,status,timeout_ms,created_at) VALUES('old-job','summarize-text','保留输入','failed',10000,'fixture')",[]).unwrap();s.db.execute_batch("ALTER TABLE agent_jobs DROP COLUMN context_objects;ALTER TABLE agent_jobs DROP COLUMN ordinal;ALTER TABLE agent_conversations DROP COLUMN deleted_at;DROP TABLE agent_deleted_sessions;ALTER TABLE todos DROP COLUMN deleted;PRAGMA user_version=13;").unwrap();drop(s);let reopened=Store::open(&root,false).unwrap();let(input,objects,ordinal):(String,String,i64)=reopened.db.query_row("SELECT input,context_objects,ordinal FROM agent_jobs WHERE id='old-job'",[],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?))).unwrap();assert_eq!(input,"保留输入");assert_eq!(objects,"[]");assert_eq!(ordinal,0);}

#[test]fn prepared_input_keeps_context_out_of_user_text(){let(mut s,p,key)=setup();let (_,context)=s.agent_prepare_input(&key,"native-fixture",1,0,&[],&[],&p).unwrap();assert_eq!(context["version"],2);assert!(context.get("draftProtocol").is_none());assert!(s.agent_drafts().unwrap().is_empty());}

#[test]fn deleting_conversation_unbinds_and_hides_it_but_preserves_inputs_and_business_drafts(){
    let(mut s,p,key)=setup();let d=draft(&mut s,&p,&key,operations());let path="C:/explicit-fixture/pi/sessions/one.jsonl";
    s.db.execute("UPDATE agent_conversations SET session_path=?,native_session_id='native-fixture' WHERE id=?",rusqlite::params![path,key]).unwrap();
    let receipt=s.agent_delete_conversation(std::slice::from_ref(&key),Some(path),"native-fixture").unwrap();assert_eq!(receipt["deleted"],true);assert!(s.agent_conversation(&key).is_err());assert!(s.agent_check_open(&key,None).is_err());assert!(s.agent_check_open("new-key",Some(path)).is_err());
    assert_eq!(s.agent_drafts().unwrap()[0]["id"],d["id"]);assert_eq!(value(&s,"one"),"旧值一");let fresh=s.agent_bind(Source{module:"today".into(),page:"today".into(),object_id:None},false).unwrap();assert_ne!(fresh["conversationKey"],key);
    let root=s.root.clone();drop(s);let s=Store::open(&root,false).unwrap();assert!(s.agent_check_open(&key,None).is_err());assert_eq!(s.agent_deleted_paths().unwrap(),vec![crate::agent_store::session_path_key(path)]);
}
#[test]fn schema14_migration_preserves_saved_sessions_and_adds_persistent_deletion(){
    let(mut s,_,key)=setup();let root=s.root.clone();s.db.execute_batch("ALTER TABLE agent_conversations DROP COLUMN deleted_at;DROP TABLE agent_deleted_sessions;ALTER TABLE todos DROP COLUMN deleted;PRAGMA user_version=14;").unwrap();drop(s);
    let s=Store::open(&root,false).unwrap();assert_eq!(s.agent_conversation(&key).unwrap()["conversationKey"],key);assert!(s.agent_deleted_paths().unwrap().is_empty());assert_eq!(s.db.query_row("PRAGMA user_version",[],|r|r.get::<_,i64>(0)).unwrap(),16);
}
