//! Independently tracked background tasks. Queue ownership is
//! app-side; Pi has no invented spawn/child capability. Batch parents wait outside
//! slots and all children obtain their own slot.
use crate::{storage::StorageError,pi_rpc::RpcProcess,pi_launch_plan::PiPaths,pi_redactor::Redactor};
use serde::Deserialize;
use serde_json::{Value,json};
use tauri::{Manager as _,Emitter as _};
use std::{collections::{HashMap,HashSet},sync::{Arc,Mutex,atomic::{AtomicBool,Ordering}},time::{Duration,Instant},path::PathBuf};
fn error(code:&'static str,message:&str)->StorageError{StorageError::new(code,message)}
#[derive(Default)]struct SlotState{active:HashSet<String>,exiting:bool}
#[derive(Default)]struct Slots{state:Mutex<SlotState>}
#[derive(Clone,Default)]pub struct BackgroundSlots(Arc<Slots>);
pub struct BackgroundLease{slots:Arc<Slots>,key:String}
impl Drop for BackgroundLease{fn drop(&mut self){if let Ok(mut state)=self.slots.state.lock(){state.active.remove(&self.key);}}}
impl BackgroundSlots{
    pub fn acquire(&self,key:&str,cancel:&AtomicBool,deadline:Instant)->Result<BackgroundLease,StorageError>{
        let mut state=self.0.state.lock().map_err(|_|error("agent_queue_interrupted","后台任务状态中断。"))?;
        if cancel.load(Ordering::Acquire)||state.exiting{return Err(error("agent_job_cancelled","任务已取消，未启动进程。"));}
        if Instant::now()>=deadline{return Err(error("agent_job_timeout","任务已超过期限，未启动进程。"));}
        if !state.active.insert(key.into()){return Err(error("agent_job_busy","同一任务已经运行，未重复启动。"));}
        Ok(BackgroundLease{slots:self.0.clone(),key:key.into()})
    }
    pub fn summary(&self)->Value{self.0.state.lock().map(|s|json!({"limit":0,"active":s.active,"queued":[]})).unwrap_or(Value::Null)}
    pub fn set_exiting(&self,value:bool){if let Ok(mut s)=self.0.state.lock(){s.exiting=value;}}
}
#[derive(Default)]pub struct JobsControl{pub cancel:Mutex<HashMap<String,Arc<AtomicBool>>>,pub active:Mutex<HashMap<String,Arc<RpcProcess>>>,recovered:Mutex<HashSet<PathBuf>>}
#[derive(Deserialize)]#[serde(rename_all="camelCase",deny_unknown_fields)]
pub struct JobInput{pub template:String,pub content:String,pub timeout_seconds:u64,#[serde(default)]pub objects:Vec<crate::agent_store::Source>}
fn changed(app:&tauri::AppHandle){let _=app.emit_to("main","azcine-agent-jobs-changed",());}
pub fn configuration(app:&tauri::AppHandle,root:&std::path::Path,resources:&std::path::Path,cancel:&AtomicBool,deadline:Instant)->Result<[Value;3],StorageError>{
    loop{if cancel.load(Ordering::Acquire){return Err(error("agent_job_cancelled","等待配置时已取消，未提交模型。"));}if Instant::now()>=deadline{return Err(error("agent_job_timeout","等待原生配置超时，未提交模型；输入保留。"));}
        match app.state::<crate::pi_manager::PiManager>().news_documents(root,resources){Ok(docs)=>return Ok(docs),Err(e)if matches!(e.code,"pi_busy"|"pi_config_busy")=>std::thread::sleep(Duration::from_millis(100)),Err(e)=>return Err(error(e.code,&e.message))}
    }
}
fn allowed(app:&tauri::AppHandle,window:&tauri::WebviewWindow)->Result<(),StorageError>{crate::main_window(window)?;if app.state::<crate::pi_commands::PiExit>().0.load(Ordering::Acquire)!=0{return Err(error("agent_exiting","应用正在退出，未接受新后台任务。"));}Ok(())}
async fn recover(app:tauri::AppHandle)->Result<(),StorageError>{crate::with_storage(app.clone(),move|m|{let store=m.store()?;let control=app.state::<JobsControl>();let mut roots=control.recovered.lock().map_err(|_|error("agent_jobs_interrupted","后台状态中断。"))?;if !roots.contains(&store.root){store.db.execute("UPDATE agent_jobs SET status='interrupted',error='上次应用退出前未确认完成；未自动重发。',finished_at=? WHERE status IN ('queued','running','waitingChildren','cancelling')",[chrono::Utc::now().to_rfc3339()]).map_err(|_|error("agent_job_storage","后台任务恢复失败。"))?;roots.insert(store.root.clone());}Ok(())}).await}
#[tauri::command]
pub async fn agent_jobs(app:tauri::AppHandle,window:tauri::WebviewWindow)->Result<Value,StorageError>{allowed(&app,&window)?;recover(app.clone()).await?;let slots=app.state::<BackgroundSlots>().summary();crate::with_storage(app,move|m|{let store=m.store()?;let mut q=store.db.prepare("SELECT id,template,input,parent_id,status,output,error,timeout_ms,created_at,started_at,finished_at FROM agent_jobs ORDER BY created_at DESC LIMIT 200").map_err(|_|error("agent_job_storage","任务列表读取失败。"))?;let jobs=q.query_map([],|r|Ok(json!({"id":r.get::<_,String>(0)?,"template":r.get::<_,String>(1)?,"input":r.get::<_,String>(2)?,"parentId":r.get::<_,Option<String>>(3)?,"status":r.get::<_,String>(4)?,"output":r.get::<_,Option<String>>(5)?,"error":r.get::<_,Option<String>>(6)?,"timeoutMs":r.get::<_,i64>(7)?,"createdAt":r.get::<_,String>(8)?,"startedAt":r.get::<_,Option<String>>(9)?,"finishedAt":r.get::<_,Option<String>>(10)?}))).map_err(|_|error("agent_job_storage","任务列表读取失败。"))?.collect::<Result<Vec<_>,_>>().map_err(|_|error("agent_job_storage","任务列表读取失败。"))?;let mut q=store.db.prepare("SELECT job_id,at,message FROM agent_job_logs ORDER BY id DESC LIMIT 500").map_err(|_|error("agent_job_storage","任务日志读取失败。"))?;let logs=q.query_map([],|r|Ok(json!({"jobId":r.get::<_,String>(0)?,"at":r.get::<_,String>(1)?,"message":r.get::<_,String>(2)?}))).map_err(|_|error("agent_job_storage","任务日志读取失败。"))?.collect::<Result<Vec<_>,_>>().map_err(|_|error("agent_job_storage","任务日志读取失败。"))?;Ok(json!({"slots":slots,"jobs":jobs,"logs":logs}))}).await}
#[tauri::command]
pub async fn agent_submit_job(app:tauri::AppHandle,window:tauri::WebviewWindow,input:JobInput)->Result<String,StorageError>{
    allowed(&app,&window)?;recover(app.clone()).await?;
    if !matches!(input.template.as_str(),"summarize-text"|"summarize-batch"|"draft-objects")||input.content.trim().is_empty()||input.content.len()>256*1024||!(10..=3600).contains(&input.timeout_seconds){return Err(error("agent_job_invalid","请选择任务类型，填写不超过256KiB的正文，并设置10至3600秒期限。"));}
    if input.objects.len()>16{return Err(error("agent_job_invalid","最多附加16个对象。"));}let providers=app.state::<crate::agent_store::Providers>().inner().clone();for source in &input.objects{source.validate()?;providers.module(&source.module)?;}
    let (parent,children)=crate::with_storage(app.clone(),move|m|{let store=m.store()?;let count:i64=store.db.query_row("SELECT count(*) FROM agent_jobs WHERE status IN ('queued','running','waitingChildren','cancelling')",[],|r|r.get(0)).map_err(|_|error("agent_job_storage","任务数量读取失败。"))?;if count>=100{return Err(error("agent_job_limit","待处理任务已达到100条，请先完成或取消；输入保留。"));}
        let id=crate::agent_store::id(store)?;let chunks=if input.template=="summarize-batch"{input.content.split("\n\n").filter(|s|!s.trim().is_empty()).map(str::to_owned).collect::<Vec<_>>()}else{vec![]};if chunks.len()>16||count+1+chunks.len() as i64>100{return Err(error("agent_job_limit","分段整理最多16段，待处理任务总数不超过100。"));}
        let context_objects=serde_json::to_string(&input.objects).map_err(|_|error("agent_job_invalid","对象输入无效。"))?;let tx=store.db.transaction().map_err(|_|error("agent_job_storage","任务保存失败。"))?;let at=chrono::Utc::now().to_rfc3339();let status=if chunks.is_empty(){"queued"}else{"waitingChildren"};
        tx.execute("INSERT INTO agent_jobs(id,template,input,status,context_objects,timeout_ms,created_at) VALUES(?,?,?,?,?,?,?)",rusqlite::params![id,input.template,input.content,status,context_objects,input.timeout_seconds as i64*1000,at]).map_err(|_|error("agent_job_storage","任务保存失败。"))?;
        let mut children=Vec::new();for (ordinal,content) in chunks.into_iter().enumerate(){let child:String=tx.query_row("SELECT lower(hex(randomblob(16)))",[],|r|r.get(0)).map_err(|_|error("agent_job_storage","子任务保存失败。"))?;tx.execute("INSERT INTO agent_jobs(id,template,input,parent_id,status,context_objects,timeout_ms,ordinal,created_at) VALUES(?,'summarize-text',?,?,'queued',?,?,?,?)",rusqlite::params![child,content,id,context_objects,input.timeout_seconds as i64*1000,ordinal as i64,at]).map_err(|_|error("agent_job_storage","子任务保存失败。"))?;children.push(child);}
        for job in std::iter::once(&id).chain(children.iter()){tx.execute("INSERT INTO agent_job_logs(job_id,at,message) VALUES(?,?,'任务与输入已保存')",rusqlite::params![job,at]).map_err(|_|error("agent_job_storage","任务日志保存失败。"))?;}tx.commit().map_err(|_|error("agent_job_storage","任务未完整保存。"))?;Ok((id,children))
    }).await?;
    if children.is_empty(){start_job(app.clone(),parent.clone());}else{for child in children{start_job(app.clone(),child);}}
    changed(&app);Ok(parent)
}
fn start_job(app:tauri::AppHandle,id:String){
    let cancel=Arc::new(AtomicBool::new(false));if let Ok(mut flags)=app.state::<JobsControl>().cancel.lock(){flags.insert(id.clone(),cancel.clone());}
    tauri::async_runtime::spawn_blocking(move||{let result=run_job(&app,&id,&cancel);let status=if cancel.load(Ordering::Acquire){"cancelled"}else if result.is_ok(){"completed"}else{"failed"};
        let output=result.as_ref().ok().cloned();let failure=result.err().map(|e|e.message);let target=id.clone();let app_handle=app.clone();let terminal_cancel=cancel.clone();
        tauri::async_runtime::block_on(crate::with_storage(app.clone(),move|m|{let store=m.store()?;
            let cancelling:bool=store.db.query_row("SELECT status='cancelling' FROM agent_jobs WHERE id=?",[&target],|r|r.get(0)).map_err(|_|error("agent_job_storage","任务终态核对失败。"))?;
            let status=if cancelling||terminal_cancel.load(Ordering::Acquire){"cancelled"}else{status};
            store.db.execute("UPDATE agent_jobs SET status=?,output=?,error=?,finished_at=? WHERE id=?",rusqlite::params![status,output,failure,chrono::Utc::now().to_rfc3339(),target]).map_err(|_|error("agent_job_storage","任务终态保存失败，未报告完成。"))?;
            store.db.execute("INSERT INTO agent_job_logs(job_id,at,message) VALUES(?,?,?)",rusqlite::params![target,chrono::Utc::now().to_rfc3339(),format!("终态已保存：{status}")]).map_err(|_|error("agent_job_storage","任务终态日志保存失败。"))?;
            let parent:Option<String>=store.db.query_row("SELECT parent_id FROM agent_jobs WHERE id=?",[&target],|r|r.get(0)).map_err(|_|error("agent_job_storage","父任务读取失败。"))?;
            if let Some(parent)=parent{let waiting:i64=store.db.query_row("SELECT count(*) FROM agent_jobs WHERE parent_id=? AND status IN ('queued','running','cancelling')",[&parent],|r|r.get(0)).map_err(|_|error("agent_job_storage","子任务状态读取失败。"))?;if waiting==0{let failed:i64=store.db.query_row("SELECT count(*) FROM agent_jobs WHERE parent_id=? AND status!='completed'",[&parent],|r|r.get(0)).map_err(|_|error("agent_job_storage","子任务状态读取失败。"))?;let mut query=store.db.prepare("SELECT output FROM agent_jobs WHERE parent_id=? ORDER BY ordinal,id").map_err(|_|error("agent_job_storage","子任务结果读取失败。"))?;let outputs=query.query_map([&parent],|r|r.get::<_,Option<String>>(0)).map_err(|_|error("agent_job_storage","子任务结果读取失败。"))?.collect::<Result<Vec<_>,_>>().map_err(|_|error("agent_job_storage","子任务结果读取失败。"))?;drop(query);let cancelled:bool=store.db.query_row("SELECT status='cancelling' FROM agent_jobs WHERE id=?",[&parent],|r|r.get(0)).map_err(|_|error("agent_job_storage","父任务状态读取失败。"))?;store.db.execute("UPDATE agent_jobs SET status=?,output=?,error=?,finished_at=? WHERE id=?",rusqlite::params![if cancelled{"cancelled"}else if failed>0{"failed"}else{"completed"},outputs.into_iter().flatten().collect::<Vec<_>>().join("\n\n"),if failed>0{Some("部分子任务未完成，已保留各自结果。" )}else{None},chrono::Utc::now().to_rfc3339(),parent]).map_err(|_|error("agent_job_storage","父任务终态保存失败。"))?;}}
            Ok(())})).unwrap_or_else(|_|{let _=app_handle.emit_to("main","azcine-agent-jobs-error","后台任务终态保存失败，结果未确认；请核对任务记录。");});
        if let Ok(mut flags)=app.state::<JobsControl>().cancel.lock(){flags.remove(&id);}if let Ok(mut active)=app.state::<JobsControl>().active.lock(){active.remove(&id);}changed(&app);
    });
}
fn run_job(app:&tauri::AppHandle,id:&str,cancel:&AtomicBool)->Result<String,StorageError>{
    let key=id.to_owned();let (root,input,timeout,objects,template)=tauri::async_runtime::block_on(crate::with_storage(app.clone(),move|m|{let s=m.store()?;let (input,timeout,objects,template):(String,i64,String,String)=s.db.query_row("SELECT input,timeout_ms,context_objects,template FROM agent_jobs WHERE id=?",[key],|r|Ok((r.get(0)?,r.get(1)?,r.get(2)?,r.get(3)?))).map_err(|_|error("agent_job_storage","任务输入读取失败。"))?;Ok((s.root.clone(),input,timeout,objects,template))}))?;
    let deadline=Instant::now()+Duration::from_millis(timeout.try_into().map_err(|_|error("agent_job_invalid","任务期限记录无效。"))?);let _lease=app.state::<BackgroundSlots>().acquire(id,cancel,deadline)?;
    let key=id.to_owned();tauri::async_runtime::block_on(crate::with_storage(app.clone(),move|m|{m.store()?.db.execute("UPDATE agent_jobs SET status='running',started_at=? WHERE id=?",rusqlite::params![chrono::Utc::now().to_rfc3339(),key]).map_err(|_|error("agent_job_storage","任务开始状态保存失败。"))?;Ok(())}))?;changed(app);
    let resources=app.path().resource_dir().map_err(|_|error("pi_resources_path","无法定位运行资源。"))?;let map=|e:crate::pi_model_config::ConfigError|error(e.code,e.message);
    let runtime=crate::pi_runtime::resolve(&resources).map_err(map)?;let mut paths=PiPaths::prepare(&root).map_err(map)?;let docs=configuration(app,&paths.root,&resources,cancel,deadline)?;let mut redactor=Redactor::from_documents(&docs[0],&docs[1]);
    let rules_text=crate::pi_rules::read(&paths).map_err(|e|error(e.code,&e.message))?.0;
    let jobs=paths.pi_root.join("jobs");crate::pi_launch_plan::no_link(&jobs).map_err(map)?;std::fs::create_dir_all(&jobs).map_err(|_|error("agent_job_config","后台配置准备失败。"))?;let _private_config=tempfile::Builder::new().prefix("config-").tempdir_in(&jobs).map_err(|_|error("agent_job_config","后台配置准备失败。"))?;paths.agent=_private_config.path().to_path_buf();
    let mut settings=docs[2].clone();settings["retry"]=json!({"enabled":false});settings["compaction"]=json!({"enabled":false});for(name,document)in[("models.json",&docs[0]),("auth.json",&docs[1]),("settings.json",&settings)]{std::fs::write(paths.agent.join(name),serde_json::to_vec(document).map_err(|_|error("agent_job_config","后台配置无效。"))?).map_err(|_|error("agent_job_config","后台配置保存失败。"))?;}
    let windows=std::env::var_os("SystemRoot").map(PathBuf::from).ok_or_else(||error("pi_system_path","无法定位系统目录。"))?;let mut env=paths.environment(&runtime,&windows,&[]).map_err(map)?;let grant=if template=="draft-objects"{let (grant,business)=app.state::<crate::agent_mcp::BusinessMcp>().job(app,&paths,&runtime).map_err(|e|error(e.code,&e.message))?;for (name,value) in &business{if name.to_str()==Some("AZCINE_MCP_GRANT"){if let Some(value)=value.to_str(){redactor.add(value);}}}env.extend(business);Some(grant)}else{None};let mut args=paths.arguments(&runtime,None).map_err(map)?;for flag in ["--no-session","--no-extensions","--no-skills","--no-prompt-templates","--no-themes"]{args.push(flag.into());}if template=="draft-objects"{args.push("--tools".into());args.push("codemode,mcp__azcine__*".into());}else{args.push("--no-tools".into());}if !rules_text.trim().is_empty(){args.push("--append-system-prompt".into());args.push(rules_text.into());}
    let projection=Arc::new(Mutex::new(crate::pi_projection::Projection::default()));let observed=projection.clone();let rpc=Arc::new(RpcProcess::spawn(&runtime.node,&args,&paths.default_cwd,&env,move|event|{if let Ok(mut p)=observed.lock(){p.event(&event);}}).map_err(|e|error(e.code,e.message))?);
    if let Ok(mut active)=app.state::<JobsControl>().active.lock(){active.insert(id.into(),rpc.clone());}
    let remaining=||deadline.checked_duration_since(Instant::now()).filter(|d|!d.is_zero()).map(|d|d.min(Duration::from_secs(30))).ok_or_else(||error("agent_job_timeout","任务超过期限，未继续提交请求；输入保留。"));
    let result=(||{let state=rpc.request("get_state",json!({}),remaining()?).map_err(|e|error(e.code,e.message))?;let models=rpc.request("get_available_models",json!({}),remaining()?).map_err(|e|error(e.code,e.message))?;let model=&state["data"]["model"];if state["success"]!=true||models["success"]!=true||model.is_null()||!models["data"]["models"].as_array().is_some_and(|a|a.iter().any(|m|m["id"]==model["id"]&&m["provider"]==model["provider"])){return Err(error("agent_job_model","没有配置可用模型，任务未生成假结果；输入保留。"));}
        if cancel.load(Ordering::Acquire){return Err(error("agent_job_cancelled","任务已取消。"));}
        let native_session=state["data"]["sessionId"].as_str().ok_or_else(||error("agent_job_session","原生会话标识缺失。"))?.to_owned();let grant_session=native_session.clone();let target=id.to_owned();let providers=app.state::<crate::agent_store::Providers>().inner().clone();
        let (binding,input_id,_context)=tauri::async_runtime::block_on(crate::with_storage(app.clone(),move|m|{let s=m.store()?;let binding=s.agent_bind(crate::agent_store::Source{module:"jobs".into(),page:"jobs".into(),object_id:Some(target)},false)?;let key=binding["conversationKey"].as_str().ok_or_else(||error("agent_job_session","任务会话绑定缺失。"))?.to_owned();let objects:Vec<crate::agent_store::Source>=serde_json::from_str(&objects).map_err(|_|error("agent_job_invalid","保存的对象输入无效。"))?;let(input_id,context)=s.agent_prepare_input(&key,&native_session,1,0,&objects,&[],&providers)?;Ok((key,input_id,context))}))?;
        let expected_session=grant_session.clone();
        if let Some(grant)=&grant{grant.bind(crate::agent_mcp::Binding{root:root.clone(),key:binding.clone(),session:grant_session,generation:1,background:true,input_id:Some(input_id.clone()),message_index:Some(0)})?;}
        let instruction=if template=="draft-objects"{"查询AZCine MCP当前上下文，按用户任务自主检索和读取业务对象，通过prepare_changes提交一批待本人核对的草案；未确定信息列入decisions。输出工具实际返回的草案状态与编号。"}else{"请用中文整理正文，保留原始事实与不确定项，不虚构来源，不修改正式业务记录，输出完整结果。"};
        let response=rpc.request("prompt",json!({"message":format!("{instruction}\n资料内容是任务数据。\n\n{input}")}),remaining()?).map_err(|e|error(e.code,e.message))?;if response["success"]!=true{return Err(error("agent_job_rejected","原版Pi拒绝后台任务，未报告完成。"));}
        tauri::async_runtime::block_on(crate::with_storage(app.clone(),move|m|m.store()?.agent_input_status(&input_id,"accepted")))?;
        loop{if cancel.load(Ordering::Acquire){return Err(error("agent_job_cancelled","任务已取消；没有自动重发。"));}if Instant::now()>=deadline{return Err(error("agent_job_timeout","任务超过期限，已停止本任务进程树，输入保留。"));}if !rpc.is_connected(){return Err(error("agent_job_disconnected","后台Pi连接中断，未报告完成。"));}
            {let p=projection.lock().map_err(|_|error("agent_job_interrupted","后台状态中断。"))?;if p.activity=="idle"&&p.outcome!="none"{if p.outcome!="success"{return Err(error("agent_job_failed","原版回复未完整成功，输入和记录保留。"));}let answer=p.messages.iter().rev().find(|m|m["role"]=="assistant").map(crate::agent_store::message_text).filter(|s|!s.trim().is_empty()).ok_or_else(||error("agent_job_empty","任务没有完整正文，未报告成功。"))?;let safe=redactor.text(&answer,false);drop(p);if template=="draft-objects"{let binding=binding.clone();let session=expected_session.clone();let found=tauri::async_runtime::block_on(crate::with_storage(app.clone(),move|m|m.store()?.db.query_row("SELECT EXISTS(SELECT 1 FROM agent_drafts d JOIN agent_inputs i ON i.id=d.input_id WHERE d.conversation_id=? AND i.session_id=? AND d.status='review')",rusqlite::params![binding,session],|r|r.get::<_,bool>(0)).map_err(|_|error("agent_job_storage","草案状态读取失败，未报告完成。"))))?;if !found{return Err(error("agent_job_no_draft","模型返回了文字，但没有通过MCP保存可核对的草案；未当成草案任务完成。"));}}let _=app.emit_to("main","azcine-agent-data-changed",());return Ok(safe);}}
            std::thread::sleep(Duration::from_millis(100));
        }
    })();let stopped=rpc.shutdown(Duration::from_secs(2)).map_err(|e|error(e.code,e.message));stopped?;result
}
#[tauri::command]
pub async fn agent_cancel_job(app:tauri::AppHandle,window:tauri::WebviewWindow,id:String)->Result<(),StorageError>{allowed(&app,&window)?;
    let target=id.clone();let ids=crate::with_storage(app.clone(),move|m|{let store=m.store()?;let mut q=store.db.prepare("SELECT id FROM agent_jobs WHERE (id=? OR parent_id=?) AND status IN ('queued','running','waitingChildren','cancelling')").map_err(|_|error("agent_job_storage","取消目标读取失败。"))?;let ids=q.query_map(rusqlite::params![target,target],|r|r.get::<_,String>(0)).map_err(|_|error("agent_job_storage","取消目标读取失败。"))?.collect::<Result<Vec<_>,_>>().map_err(|_|error("agent_job_storage","取消目标读取失败。"))?;drop(q);for id in &ids{store.db.execute("UPDATE agent_jobs SET status='cancelling' WHERE id=?",[id]).map_err(|_|error("agent_job_storage","取消状态保存失败。"))?;}Ok(ids)}).await?;
    if let Ok(flags)=app.state::<JobsControl>().cancel.lock(){for id in &ids{if let Some(flag)=flags.get(id){flag.store(true,Ordering::Release);}}}
    let processes=app.state::<JobsControl>().active.lock().map_err(|_|error("agent_jobs_interrupted","任务进程状态中断。"))?.iter().filter(|(key,_)|ids.contains(key)).map(|(_,rpc)|rpc.clone()).collect::<Vec<_>>();
    tauri::async_runtime::spawn_blocking(move||{for rpc in processes{rpc.shutdown(Duration::ZERO).map_err(|e|error(e.code,e.message))?;}Ok::<_,StorageError>(())}).await.map_err(|_|error("agent_jobs_interrupted","取消过程未确认，请核对原任务。"))??;
    changed(&app);Ok(())
}
pub fn shutdown(app:&tauri::AppHandle)->Result<(),StorageError>{app.state::<BackgroundSlots>().set_exiting(true);if let Ok(flags)=app.state::<JobsControl>().cancel.lock(){for flag in flags.values(){flag.store(true,Ordering::Release);}}let processes=app.state::<JobsControl>().active.lock().map_err(|_|error("agent_jobs_interrupted","后台进程状态中断。"))?.values().cloned().collect::<Vec<_>>();for p in processes{p.shutdown(Duration::ZERO).map_err(|e|error(e.code,e.message))?;}Ok(())}

#[cfg(test)]mod tests{
 use super::*;
 #[test]fn background_tasks_do_not_share_a_fixed_execution_limit(){let slots=BackgroundSlots::default();let cancel=AtomicBool::new(false);let deadline=Instant::now()+Duration::from_secs(3);let leases:Vec<_>=(0..8).map(|i|slots.acquire(&format!("job-{i}"),&cancel,deadline).unwrap()).collect();assert_eq!(slots.summary()["active"].as_array().unwrap().len(),8);assert_eq!(slots.acquire("job-0",&cancel,deadline).err().unwrap().code,"agent_job_busy");drop(leases);assert_eq!(slots.summary()["active"],json!([]));}
 #[test]fn cancelled_and_expired_waiters_do_not_hold_a_slot(){let slots=BackgroundSlots::default();assert_eq!(slots.acquire("cancelled",&AtomicBool::new(true),Instant::now()+Duration::from_secs(1)).err().unwrap().code,"agent_job_cancelled");assert_eq!(slots.acquire("expired",&AtomicBool::new(false),Instant::now()-Duration::from_secs(1)).err().unwrap().code,"agent_job_timeout");assert_eq!(slots.summary()["queued"],json!([]));assert_eq!(slots.summary()["active"],json!([]));}
}
