//! Retained synthetic reader fixtures; never open the user's business data.
use crate::{storage::Store,news_types::Material,news_reader_types::{Article,PipelineConfig},news_reader_store::{encode,decode},news_editorial_types::EditorialRun};
use rusqlite::params;
use serde_json::{json,Value};
use std::{path::PathBuf,fs};
fn id(n:u32)->String{format!("ccddeeff-1111-2222-3333-{n:012x}")}
fn store()->Store{let base=PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../artifacts/validation");fs::create_dir_all(&base).unwrap();let root=tempfile::Builder::new().prefix("news-reader-").tempdir_in(base).unwrap().keep().join("data");Store::open(&root,true).unwrap()}
fn material(s:&mut Store,n:u32)->Material{let source=s.news_sources().unwrap().remove(0);let work=s.begin_news_batch(&id(n),Some(&source.config.id)).unwrap().unwrap().remove(0);let xml=format!("<rss xmlns:content=\"http://purl.org/rss/1.0/modules/content/\"><channel><item><guid>reader-{n}</guid><title>显式测试新闻 {n}</title><link>https://example.org/reader/{n}</link><description>测试摘要</description><content:encoded><![CDATA[<h2>公开范围</h2><p>{}</p><h2>价格与限制</h2><p>读取免费，导出需要消耗额度。</p><ul><li>第一条限制</li><li>第二条限制</li></ul><pre><code>const count = 2;</code></pre>]]></content:encoded></item></channel></rss>","这是保留的显式虚构正文，用于核对阅读体验，不代表真实新闻。".repeat(48));let feed=crate::news_feed::parse(xml.as_bytes(),"https://example.org/rss").unwrap();s.save_news_materials(&work,&feed,&crate::news_store::now()).unwrap();s.news_materials(Some(&source.config.id),0).unwrap().items.into_iter().find(|m|m.url==format!("https://example.org/reader/{n}")).unwrap()}
fn article(s:&Store,m:Material)->Article{let hash=crate::news_prompts::hash(&m.id);let body=s.reader_body(&m.id).unwrap().unwrap().0;Article{legacy_event_id:None,id:m.id.clone(),material:m,title_zh:"显式测试：新产品开放公开预览，读取免费，导出仍消耗额度".into(),summary_zh:"这款虚构产品开放公开预览。读取功能免费，导出仍需要消耗额度，两项操作的条件分别保留。测试资料用于核对排版与存储，不能作为真实新闻或模型效果的证明。".into(),reason:"公开范围与收费条件有明确变化，读者可以直接确认适用范围。".into(),category:Some("ai-products".into()),tags:vec!["产品更新".into()],subjects:vec![],scope:"single".into(),fact:Value::Null,score_first:Some(80),score_second:Some(90),score:Some(85.),tier:"T1".into(),selected:true,adds_value:true,selection_reason:String::new(),occurrence_id:hash.clone(),story_id:hash,original_body:body,translated_body:None,body_kind:"feed".into(),body_error:None,display_body:true,translation_complete:false,translation_error:None,status:"ready".into(),processed_at:crate::news_store::now(),config_revision:1,upstream:crate::news_prompts::UPSTREAM.into()}}
fn run(s:&Store,n:u32)->EditorialRun{s.start_editorial_run(&id(n),"organize",None).unwrap().0}
#[test]fn given_failed_receipt_when_manually_starting_a_new_task_then_only_explicit_attempt_is_reserved_and_original_failure_is_retained(){let mut s=store();let p=PipelineConfig::default();let model=json!({"provider":"explicit","id":"fixture"});let failed=s.reader_start_step("same-input",&id(1),"material","structure",&model,"hash","input",&p,false).unwrap();s.reader_finish_step(failed,Some("retained invalid response"),&Value::Null,Some("explicit validation failure")).unwrap();assert_eq!(s.reader_start_step("same-input",&id(2),"material","structure",&model,"hash","input",&p,false).unwrap_err().code,"news_step_retry_required");assert_eq!(s.reader_failed_response("same-input").unwrap().as_deref(),Some("retained invalid response"));let retry=s.reader_start_step("same-input",&id(2),"material","structure",&model,"hash","input",&p,true).unwrap();assert_ne!(retry,failed);assert_eq!(s.reader_start_step("same-input",&id(3),"material","structure",&model,"hash","input",&p,true).unwrap_err().code,"news_step_running");assert_eq!(s.db.query_row("SELECT status FROM news_step_receipts WHERE id=?1",[failed],|r|r.get::<_,String>(0)).unwrap(),"failed");}
#[test]fn full_feed_body_survives_summary_limits_and_untrusted_markup(){let mut s=store();let m=material(&mut s,1);let (body,kind,_)=s.reader_body(&m.id).unwrap().unwrap();assert_eq!(kind,"feed");assert!(body.chars().count()>1000);assert!(body.contains("## 价格与限制"));assert!(body.contains("const count = 2;"));let md=crate::news_content::markdown("<h2>可见</h2><script>secret()</script><p><a href=\"javascript:alert(1)\">链接</a><img src=\"http://127.0.0.1/private\" /></p>","https://example.org",false).unwrap();assert!(md.contains("## 可见"));assert!(!md.contains("secret"));assert!(!md.contains("javascript"));assert!(!md.contains("127.0.0.1"));}
#[test]fn atom_xhtml_keeps_real_headings_lists_and_links(){let feed=crate::news_feed::parse(br#"<feed xmlns="http://www.w3.org/2005/Atom"><entry><title>Fixture</title><link href="https://example.org/item"/><content type="xhtml"><div xmlns="http://www.w3.org/1999/xhtml"><h2>Scope</h2><p>Read <a href="https://example.org/docs">docs</a></p><ul><li>Condition</li></ul></div></content></entry></feed>"#,"https://example.org/feed").unwrap();let b=feed.entries[0].body.as_ref().unwrap();assert!(b.contains("## Scope"));assert!(b.contains("[docs](https://example.org/docs)"));assert!(b.contains("- Condition"));assert!(!feed.entries[0].body_full); // Short content stays available without claiming a full article.
}
#[test]fn successful_paid_steps_reuse_and_failed_steps_require_explicit_retry(){let mut s=store();let p=PipelineConfig{requests_per_minute:2,..Default::default()};let model=json!({"provider":"fixture","id":"fixture"});let a=s.reader_start_step("a","run","material","scoreFirst",&model,"hash","input",&p,false).unwrap();s.reader_finish_step(a,Some("{\"attentionScore\":80}"),&json!({"input":10,"output":10}),None).unwrap();assert!(s.reader_cached_step("a").unwrap().is_some());let b=s.reader_start_step("b","run","material","scoreSecond",&model,"hash","input",&p,false).unwrap();s.reader_finish_step(b,Some("bad"),&Value::Null,Some("Invalid JSON")).unwrap();assert!(s.reader_cached_step("b").unwrap().is_none());assert_eq!(s.reader_start_step("b","run","material","scoreSecond",&model,"hash","input",&p,false).unwrap_err().code,"news_step_retry_required");assert_eq!(s.reader_start_step("c","run","material","structure",&model,"hash","input",&p,false).unwrap_err().code,"news_request_quota");let unlimited=PipelineConfig{requests_per_minute:0,requests_per_hour:0,requests_per_day:0,..p};let retry=s.reader_start_step("b","run","material","scoreSecond",&model,"hash","input",&unlimited,true).unwrap();assert_ne!(retry,b);}
#[test]fn article_commit_failure_rolls_back_article_marker_and_run_count(){let mut s=store();let m=material(&mut s,1);let a=article(&s,m);let mut r=run(&s,2);s.db.execute_batch("CREATE TRIGGER explicit_fail BEFORE INSERT ON news_processed BEGIN SELECT RAISE(ABORT,'fixture'); END;").unwrap();assert!(s.reader_commit(&a,&mut r).is_err());assert_eq!(r.processed,0);assert!(s.reader_article(&a.id).is_err());s.db.execute_batch("DROP TRIGGER explicit_fail").unwrap();s.reader_commit(&a,&mut r).unwrap();s.reader_commit(&a,&mut r).unwrap();assert_eq!(r.processed,1);assert_eq!(s.editorial_snapshot().unwrap().pending,0);assert_eq!(s.reader_snapshot("featured","","",100).unwrap()["total"],1);}
#[test]fn daily_cutoff_uses_original_run_and_excludes_late_processing(){let mut s=store();let m=material(&mut s,1);let mut a=article(&s,m);a.material.published_at=Some("2026-10-03T18:00:00Z".into());a.processed_at="2026-10-03T20:00:00Z".into();let mut r=run(&s,2);s.reader_commit(&a,&mut r).unwrap();r.started_at="2026-10-04T04:00:00Z".into();let e=crate::news_reader_editions::daily(&mut s,&r).unwrap();assert_eq!(e["date"],"2026-10-04");assert_eq!(e["main"].as_array().unwrap().len(),1);a.processed_at="2026-10-04T01:00:00Z".into();s.db.execute("UPDATE news_articles SET payload=?1 WHERE id=?2",params![encode(&a).unwrap(),a.id]).unwrap();let same=crate::news_reader_editions::daily(&mut s,&r).unwrap();assert_eq!(same,e);r.id=id(3);let next=crate::news_reader_editions::daily(&mut s,&r).unwrap();assert!(next["main"].as_array().unwrap().is_empty());}
#[test]fn reader_metadata_omits_full_bodies_but_detail_and_bookmark_persist(){let mut s=store();let m=material(&mut s,1);let a=article(&s,m);let mut r=run(&s,2);s.reader_commit(&a,&mut r).unwrap();s.db.execute("UPDATE news_articles SET bookmarked=1,reading_position=0.4 WHERE id=?1",[&a.id]).unwrap();let snapshot=s.reader_snapshot("bookmarks","","",100).unwrap();assert_eq!(snapshot["total"],1);assert!(snapshot["items"][0].get("originalBody").is_none());let detail=s.reader_detail(&a.id).unwrap();assert_eq!(detail["position"],0.4);assert_eq!(detail["bookmarked"],true);assert_eq!(detail["article"]["originalBody"],a.original_body);let root=s.root.clone();drop(s);let s=Store::open(&root,false).unwrap();assert_eq!(s.reader_detail(&a.id).unwrap()["position"],0.4);}
#[test]fn upstream_templates_expand_without_installing_pi_skills(){let variables=crate::news_prompts::variables();for name in ["prefilter","selection-score","understand","structure","group-pair","story-digest","translate-body"]{let (prompt,hash)=crate::news_prompts::render(name,&variables).unwrap();assert!(!prompt.contains("{{"));assert_eq!(hash.len(),64);}assert!(crate::news_prompts::source("missing").is_err());}
#[test]fn prepare_explicit_reader_desktop_fixture(){let mut s=store();let mut r=run(&s,1000);for n in 10..16{let m=material(&mut s,n);let mut a=article(&s,m);a.title_zh=format!("显式测试报道 {n}：产品开放范围与收费条件更新");a.material.published_at=Some((chrono::Utc::now()-chrono::Duration::hours(i64::from(n-9))).to_rfc3339());a.material.discovered_at=a.material.published_at.clone().unwrap();a.processed_at=(chrono::Utc::now()-chrono::Duration::hours(30)).to_rfc3339();s.reader_commit(&a,&mut r).unwrap();}let m=material(&mut s,1);let metadata=json!({"mode":"explicit synthetic reader fixture; no live inference","root":s.root,"pendingId":m.id,"articles":6});fs::write(s.root.parent().unwrap().join("reader-desktop-fixture.json"),serde_json::to_vec_pretty(&metadata).unwrap()).unwrap();assert_eq!(s.editorial_snapshot().unwrap().pending,1);let _:Article=decode(&encode(&s.reader_article(&s.reader_snapshot("all","","",100).unwrap()["items"][0]["id"].as_str().unwrap()).unwrap()).unwrap()).unwrap();}
#[test]fn prepare_explicit_extended_reader_fixture(){let mut s=store();let mut ids=Vec::new();for n in 1..=4{let m=material(&mut s,n);let title=match n{1|2=>"EXPLICIT FixtureLabs releases Reader public preview",3=>"EXPLICIT blockedFixture ordinary daily post",_=>"EXPLICIT lowFixture product note"};s.db.execute("UPDATE news_materials SET title=?1 WHERE id=?2",params![title,m.id]).unwrap();if n<=2{s.reader_save_body(&m.id,"## Public scope\n\nFixtureLabs released Reader public preview. Reading is free.\n\n## Pricing and limits\n\nExports consume credits. See [documentation](https://example.org/docs).\n\n```js\nconst price = 2;\n```","feed",None).unwrap();}ids.push(m.id);}let mut r=run(&s,1000);for n in 10..12{let m=material(&mut s,n);let mut a=article(&s,m);a.scope="composite".into();a.fact=Value::Null;a.title_zh=format!("显式期间测试报道 {n}");let at=(chrono::Utc::now()-chrono::Duration::days(if n==10{3}else{10})).to_rfc3339();a.material.published_at=Some(at.clone());a.material.discovered_at=at.clone();a.processed_at=at;s.reader_commit(&a,&mut r).unwrap();}let meta=json!({"mode":"explicit synthetic extended fixture; no live inference","root":s.root,"pendingIds":ids});fs::write(s.root.parent().unwrap().join("reader-extended-fixture.json"),serde_json::to_vec_pretty(&meta).unwrap()).unwrap();assert_eq!(s.editorial_snapshot().unwrap().pending,4);}

#[test]fn unknown_prefilter_keeps_nonempty_but_insufficient_material_pending(){let readiness=crate::news_pipeline::prefilter_readiness;assert_eq!(readiness("UNKNOWN","看视频了解它的变化").unwrap_err().code,"news_awaiting_body");assert!(readiness("PASS","").is_ok());assert_eq!(readiness("BLOCK","").unwrap_err().code,"news_awaiting_body");assert!(readiness("BLOCK","今天午餐吃了面条").is_ok());}

#[test]fn invalid_translation_keeps_reporting_readable_and_retry_only_updates_translation(){
    let mut s=store();let m=material(&mut s,1);let mut a=article(&s,m);let mut r=run(&s,2);
    let model=json!({"provider":"fixture","id":"fixture"});
    let step=s.reader_start_step("explicit-bad-translation",&r.id,&a.id,"translateBody",&model,"hash","fixture input",&PipelineConfig::default(),false).unwrap();
    s.reader_finish_step(step,Some("invalid JSON"),&Value::Null,Some("invalid JSON")).unwrap();
    crate::news_pipeline::apply_translation(&mut a,Err(crate::storage::StorageError::new("news_ai_invalid","fixture invalid JSON"))).unwrap();
    s.reader_commit(&a,&mut r).unwrap();
    assert_eq!(r.processed,1);assert_eq!(s.reader_snapshot("all","","",100).unwrap()["total"],1);
    let saved=s.reader_article(&a.id).unwrap();assert_eq!(saved.summary_zh,a.summary_zh);assert_eq!(saved.original_body,a.original_body);assert!(saved.translated_body.is_none());assert!(saved.translation_error.is_some());
    assert!(s.reader_cached_step("explicit-bad-translation").unwrap().is_none());
    s.db.execute("UPDATE news_articles SET bookmarked=1,reading_position=0.4 WHERE id=?1",[&a.id]).unwrap();
    let published_at=a.processed_at.clone();let title=a.title_zh.clone();let score=a.score;
    crate::news_pipeline::apply_translation(&mut a,Ok("显式虚构译文".into())).unwrap();
    // Updating translation must not overwrite already published editorial data.
    a.title_zh="must not replace saved title".into();a.processed_at="must not replace publication time".into();a.score=Some(0.);
    s.reader_update_translation(&a).unwrap();
    let saved=s.reader_article(&a.id).unwrap();assert_eq!(saved.title_zh,title);assert_eq!(saved.processed_at,published_at);assert_eq!(saved.score,score);assert_eq!(saved.translated_body.as_deref(),Some("显式虚构译文"));assert!(saved.translation_error.is_none());assert!(saved.translation_complete);
    let detail=s.reader_detail(&a.id).unwrap();assert_eq!(detail["bookmarked"],true);assert_eq!(detail["position"],0.4);
    assert_eq!(s.db.query_row("SELECT count(*) FROM news_processed",[],|r|r.get::<_,i64>(0)).unwrap(),1);assert_eq!(r.processed,1);
}
#[test]fn cancellation_is_not_treated_as_optional_translation_failure(){
    let mut s=store();let m=material(&mut s,1);let mut a=article(&s,m);
    let error=crate::news_pipeline::apply_translation(&mut a,Err(crate::storage::StorageError::new("news_cancelled","fixture cancellation"))).unwrap_err();
    assert_eq!(error.code,"news_cancelled");assert!(a.translation_error.is_none());assert!(s.reader_article(&a.id).is_err());
}
#[test]fn quoted_css_selectors_do_not_leak_html_attributes_into_article_text(){
    let prose="Explicit synthetic article text for parser regression. ".repeat(6);
    let html=format!("<article class=\"[&>a]:hidden\"><h2 class=\"[&>span]:mb-0\">Scope</h2><p>{prose}<a class='[&>i]:hidden' href='/docs'>documentation</a></p></article>");
    let body=crate::news_content::markdown(&html,"https://example.org/item",true).unwrap();
    assert!(body.contains("## Scope"));assert!(body.contains(&prose));assert!(body.contains("[documentation](https://example.org/docs)"));assert!(!body.contains("hidden"));assert!(!body.contains("mb-0"));
}

#[test]fn given_html_href_with_bare_ampersand_when_resolving_aggregator_then_keep_original_link(){
    let base = "https://www.techmeme.com/261007/p42";
    let title = "Example researchers request preserving visibility into model reasoning (Example Journal)";
    let original = "https://example.org/article?st=sample&reflink=desktopwebshare_permalink";
    let html = format!("<a href=\"{original}\">Example researchers request preserving visibility into model reasoning</a>");
    assert_eq!(crate::news_content::page_original(&html, base, title).as_deref(), Some(original));
    let body = crate::news_content::markdown(&html, base, false).unwrap();
    assert_eq!(crate::news_content::feed_original(&body, base, title).as_deref(), Some(original));
}

#[test]fn given_mixed_html_entities_when_decoding_then_preserve_bare_ampersands_without_losing_valid_entities(){
    assert_eq!(crate::news_content::decode_html("A & B &ldquo;quoted&rdquo; &#x4E2D; &unknown; &amp;"), "A & B “quoted” 中 &unknown; &");
    assert_eq!(crate::news_content::decode_html("?a=1&amp;b=2&c=3"), "?a=1&b=2&c=3");
    assert_eq!(crate::news_content::decode_html("&amp;lt;"), "&lt;");
    let body = crate::news_content::markdown("<a href=\"javascript&#58;alert(1)&unknown\">unsafe target</a>", "https://example.org", false).unwrap();
    assert!(!body.contains("javascript"));
}

#[test]fn saved_old_results_share_the_reader_without_reprocessing_or_replacing_state(){
    use crate::news_editorial_types::{Event,EventDraft,ModelChoice};
    let mut s=store();let m=material(&mut s,1);let event_id="d".repeat(64);
    let mut event=Event{id:event_id.clone(),revision:1,draft:EventDraft{event_key:"explicit-old".into(),material_ids:vec![m.id.clone()],domain:None,title:"已保存的原标题".into(),summary:"已保存的原导读".into(),facts:vec![],score:88,reason:"保存的推荐理由".into(),tags:vec![],limitations:vec![],needs_review:false,has_new_facts:true},materials:vec![m.clone()],generated_at:"2026-10-04T00:00:00Z".into(),latest_at:"2026-10-04T00:00:00Z".into(),config_revision:1,model:ModelChoice{provider:"fixture".into(),id:"original".into()},prompt_version:1,featured:true,analysis:None};
    s.db.execute("INSERT INTO news_events(id,payload) VALUES(?1,?2)",params![event.id,encode(&event).unwrap()]).unwrap();
    let snapshot=s.reader_snapshot("all","","",100).unwrap();assert_eq!(snapshot["total"],1);assert_eq!(snapshot["items"][0]["titleZh"],event.draft.title);assert!(snapshot["items"][0]["category"].is_null());assert!(snapshot["items"][0]["scoreFirst"].is_null());assert_eq!(snapshot["items"][0]["score"],88.0);
    s.db.execute("UPDATE news_articles SET bookmarked=1,reading_position=0.4 WHERE id=?1",[&m.id]).unwrap();
    assert_eq!(s.reader_detail(&event_id).unwrap()["bookmarked"],true);assert_eq!(s.reader_detail(&event_id).unwrap()["legacy"]["model"]["id"],"original");assert_eq!(s.reader_snapshot("all","","",100).unwrap()["total"],1);
    event.generated_at="2026-10-05T00:00:00Z".into();event.draft.title="更新后的原标题".into();s.db.execute("UPDATE news_events SET payload=?1 WHERE id=?2",params![encode(&event).unwrap(),event.id]).unwrap();assert_eq!(s.reader_detail(&event_id).unwrap()["article"]["titleZh"],event.draft.title);assert_eq!(s.reader_detail(&event_id).unwrap()["position"],0.4);
    assert_eq!(s.db.query_row("SELECT count(*) FROM news_step_receipts",[],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(s.db.query_row("SELECT count(*) FROM news_processed",[],|r|r.get::<_,i64>(0)).unwrap(),0);assert_eq!(s.editorial_event(&event_id).unwrap().draft.title,event.draft.title);
}
