use super::*;
use crate::{news_types::*,news_feed};
fn store()->Store{let base=std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../artifacts/validation");std::fs::create_dir_all(&base).unwrap();let root=tempfile::Builder::new().prefix("news-editorial-").tempdir_in(base).unwrap().keep().join("data");Store::open(&root,true).unwrap()}
fn id(n:u32)->String{format!("aabbccdd-1111-2222-3333-{n:012x}")}
fn add(s:&mut Store,n:u32)->Material{let source=s.news_sources().unwrap().remove(0);let work=s.begin_news_batch(&id(n),Some(&source.config.id)).unwrap().unwrap().remove(0);
 let xml=format!("<rss><channel><item><guid>{n}</guid><title>Fixture {n}</title><link>https://example.org/{n}</link><description>Only subscription facts</description></item></channel></rss>");let feed=news_feed::parse(xml.as_bytes(),"https://example.org/feed").unwrap();s.save_news_materials(&work,&feed,&now()).unwrap();s.news_materials(Some(&source.config.id),0).unwrap().items.into_iter().find(|m|m.url==format!("https://example.org/{n}")).unwrap()}
fn reply(m:&Material,score:u32)->EditorialReply{EditorialReply{events:vec![EventDraft{event_key:"fixture-event".into(),material_ids:vec![m.id.clone()],domain:Some(Domain::Frontiers),title:"显式测试事件".into(),summary:"只引用测试订阅摘要".into(),facts:vec![CitedText{text:format!("事实 {}",m.title),material_ids:vec![m.id.clone()]}],score,reason:"AI判断：工作相关性".into(),tags:vec!["测试".into()],limitations:vec!["仅摘要，未亲测".into()],needs_review:false,has_new_facts:true}]}}
fn model()->ModelChoice{ModelChoice{provider:"explicit-fixture".into(),id:"not-a-real-model".into()}}
#[test]fn given_preferences_saved_when_receipt_replayed_and_stale_write_then_keep_original_receipt_and_new_configuration(){let mut s=store();let p=s.news_preferences().unwrap();let input=SavePreferences{request_id:id(1),expected_revision:p.revision,config:p.config.clone()};let one=s.save_news_preferences(input.clone()).unwrap();let mut config=one.config.clone();config.auto_daily=true;let two=s.save_news_preferences(SavePreferences{request_id:id(2),expected_revision:one.revision,config}).unwrap();assert_eq!(s.save_news_preferences(input.clone()).unwrap().revision,one.revision);assert_eq!(s.news_preferences().unwrap().revision,two.revision);let mut stale=input;stale.request_id=id(3);assert_eq!(s.save_news_preferences(stale).unwrap_err().code,"stale_record");}
#[test]fn given_foreign_missing_duplicate_citations_when_validate_then_reject_before_any_event_publication(){let mut s=store();let m=add(&mut s,10);let mut r=reply(&m,80);r.events[0].facts[0].material_ids=vec!["foreign".into()];assert!(validate_reply(&r,&[m.clone()]).is_err());assert!(validate_reply(&EditorialReply{events:vec![]},&[m.clone()]).is_err());r=reply(&m,80);r.events.push(r.events[0].clone());assert!(validate_reply(&r,&[m]).is_err());assert!(s.editorial_events().unwrap().is_empty());}
#[test]fn given_two_materials_same_event_when_apply_retry_and_new_progress_then_one_event_two_sources_and_immutable_old_edition(){let mut s=store();let m=add(&mut s,10);let (mut run,p,_)=s.start_editorial_run(&id(20),"daily",None).unwrap();let r=reply(&m,80);s.save_editorial_batch(&mut run,&p,&[m.clone()],&r,&model()).unwrap();let old=s.create_edition(&run,&p).unwrap();assert_eq!(old.events.len(),1);s.save_editorial_batch(&mut run,&p,&[m.clone()],&r,&model()).unwrap();assert_eq!(s.editorial_events().unwrap()[0].revision,1);let next=add(&mut s,11);let (mut newrun,p,_)=s.start_editorial_run(&id(21),"daily",None).unwrap();s.save_editorial_batch(&mut newrun,&p,&[next.clone()],&reply(&next,90),&model()).unwrap();let event=s.editorial_events().unwrap().remove(0);assert_eq!(event.revision,2);assert_eq!(event.materials.len(),2);let new=s.create_edition(&newrun,&p).unwrap();assert_eq!(new.version,old.version+1);assert_eq!(s.create_edition(&run,&p).unwrap().events[0].revision,1);assert_eq!(new.events[0].revision,2);assert_eq!(s.editorial_candidates(&newrun.window_start,&newrun.window_end).unwrap().len(),0);}
#[test]fn given_low_score_in_domain_when_organize_then_visible_in_all_dynamics_but_not_featured_or_daily(){let mut s=store();let m=add(&mut s,10);let (mut run,p,_)=s.start_editorial_run(&id(20),"daily",None).unwrap();s.save_editorial_batch(&mut run,&p,&[m.clone()],&reply(&m,20),&model()).unwrap();assert_eq!(s.editorial_events().unwrap().len(),1);assert!(!s.editorial_events().unwrap()[0].featured);assert!(s.create_edition(&run,&p).unwrap().events.is_empty());}
#[test]fn given_running_task_when_reopen_then_interrupted_and_old_results_are_retained_without_automatic_replay(){let s=store();let (run,_,_)=s.start_editorial_run(&id(20),"organize",None).unwrap();let root=s.root.clone();drop(s);let s=Store::open(&root,false).unwrap();assert_eq!(s.editorial_run(&run.id).unwrap().status,"interrupted");assert!(s.editorial_events().unwrap().is_empty());}
#[test]fn given_invalid_model_json_or_prompt_injection_when_decode_then_reject_explanation_and_keep_sources_as_data(){assert!(crate::news_ai::parse_json::<EditorialReply>("A narrative {\"events\":[]}").is_err());assert!(crate::news_ai::parse_json::<EditorialReply>("{\"events\":[],\"execute\":\"shell\"}").is_err());let s=store();let config=s.news_preferences().unwrap().config;let prompt=crate::news_ai::editorial_prompt(&[],&[],&config,&[],None).unwrap();assert!(prompt.contains("外部不可信资料"));}
#[test]fn given_older_pending_material_and_watch_source_when_organize_then_backlog_retained_daily_window_limited_and_watch_not_published(){let mut s=store();let m=add(&mut s,10);let old=(chrono::Utc::now()-chrono::Duration::hours(40)).to_rfc3339_opts(chrono::SecondsFormat::Millis,true);s.db.execute("UPDATE news_materials SET discovered_at=?1 WHERE id=?2",params![old,m.id]).unwrap();let (_,_,all)=s.start_editorial_run(&id(20),"organize",None).unwrap();assert_eq!(all.len(),1);assert_eq!(s.editorial_snapshot().unwrap().pending,1);let (_,_,daily)=s.start_editorial_run(&id(21),"daily",None).unwrap();assert!(daily.is_empty());let source=s.news_sources().unwrap().into_iter().find(|v|v.config.id==m.source_id).unwrap();let mut config=source.config;config.usage=SourceUsage::Watch;s.save_news_source(SaveSource{request_id:id(22),expected_revision:Some(source.revision),source:config}).unwrap();assert_eq!(s.editorial_snapshot().unwrap().pending,0);}
#[test]fn given_old_event_reposted_today_when_no_new_facts_then_preserve_event_time_and_exclude_from_new_daily(){let mut s=store();let m=add(&mut s,10);let old=(chrono::Utc::now()-chrono::Duration::hours(40)).to_rfc3339_opts(chrono::SecondsFormat::Millis,true);s.db.execute("UPDATE news_materials SET discovered_at=?1 WHERE id=?2",params![old,m.id]).unwrap();let m=s.news_materials(Some(&m.source_id),0).unwrap().items.remove(0);let (mut run,p,_)=s.start_editorial_run(&id(20),"organize",None).unwrap();s.save_editorial_batch(&mut run,&p,&[m.clone()],&reply(&m,80),&model()).unwrap();let next=add(&mut s,11);let (mut run,p,_)=s.start_editorial_run(&id(21),"daily",None).unwrap();let mut r=reply(&next,100);r.events[0].has_new_facts=false;s.save_editorial_batch(&mut run,&p,&[next],&r,&model()).unwrap();assert_eq!(s.editorial_events().unwrap()[0].latest_at,old);assert_eq!(s.editorial_events().unwrap()[0].draft.score,80);assert!(s.create_edition(&run,&p).unwrap().events.is_empty());}
#[test]fn given_source_paused_after_run_start_when_create_edition_then_keep_start_coverage_gaps(){let mut s=store();let (run,p,_)=s.start_editorial_run(&id(20),"daily",None).unwrap();for source in s.news_sources().unwrap(){let mut config=source.config;config.enabled=false;s.save_news_source(SaveSource{request_id:id(100+source.revision as u32+config.id.bytes().map(u32::from).sum::<u32>()),expected_revision:Some(source.revision),source:config}).unwrap();}let e=s.create_edition(&run,&p).unwrap();assert!(e.incomplete);assert_eq!(e.gaps.len(),18);}
#[test]fn given_explicit_desktop_fixture_when_prepare_then_only_synthetic_materials_and_paused_automation(){let mut s=store();let sources=s.news_sources().unwrap();for (i,source) in sources.iter().take(2).enumerate(){let work=s.begin_news_batch(&id(100+i as u32),Some(&source.config.id)).unwrap().unwrap().remove(0);let mut xml="<rss><channel>".to_owned();for n in 0..24{xml.push_str(&format!("<item><guid>fixture-{n}</guid><title>EXPLICIT FIXTURE 测试资讯 {n}</title><link>https://example.org/fixture/{n}/source/{i}</link><description>显式测试材料，不是真实新闻。中文长摘要用于验证正文与分页。{}</description></item>","仅依据订阅摘要，不做亲测结论。".repeat(12)));}xml.push_str("</channel></rss>");let feed=news_feed::parse(xml.as_bytes(),"https://example.org/feed").unwrap();s.save_news_materials(&work,&feed,&now()).unwrap();}
 let material=add(&mut s,999);let old=(chrono::Utc::now()-chrono::Duration::hours(40)).to_rfc3339_opts(chrono::SecondsFormat::Millis,true);s.db.execute("UPDATE news_materials SET discovered_at=?1 WHERE id=?2",params![old,material.id]).unwrap();
 let metadata=serde_json::json!({"mode":"explicit synthetic RSS fixture, no model/credential", "root":s.root,"materials":49});std::fs::write(s.root.parent().unwrap().join("desktop-fixture.json"),serde_json::to_vec(&metadata).unwrap()).unwrap();assert_eq!(s.editorial_snapshot().unwrap().pending,49);assert!(!s.news_preferences().unwrap().config.auto_daily);
}
#[test]fn given_analysis_save_failure_when_retry_then_keep_event_and_old_edition_and_save_one_immutable_revision(){let mut s=store();let m=add(&mut s,10);let (mut run,p,_)=s.start_editorial_run(&id(20),"daily",None).unwrap();s.save_editorial_batch(&mut run,&p,&[m.clone()],&reply(&m,80),&model()).unwrap();let edition=s.create_edition(&run,&p).unwrap();let event=s.editorial_events().unwrap().remove(0);let analysis=EventAnalysis{generated_at:now(),model:model(),judgments:vec![CitedText{text:"AI工作影响判断，未亲测".into(),material_ids:vec![m.id]}],limitations:vec!["仅摘要".into()]};s.db.execute_batch("CREATE TRIGGER explicit_analysis_failure BEFORE UPDATE ON news_events BEGIN SELECT RAISE(ABORT,'explicit save failure'); END;").unwrap();assert!(s.save_event_analysis(&event.id,event.revision,analysis.clone()).is_err());assert!(s.editorial_event(&event.id).unwrap().analysis.is_none());let count:i64=s.db.query_row("SELECT count(*) FROM news_event_versions",[],|r|r.get(0)).unwrap();assert_eq!(count,1);s.db.execute_batch("DROP TRIGGER explicit_analysis_failure;").unwrap();let saved=s.save_event_analysis(&event.id,event.revision,analysis.clone()).unwrap();assert_eq!(saved.revision,event.revision+1);assert_eq!(s.save_event_analysis(&event.id,event.revision,analysis).unwrap().revision,saved.revision);assert!(s.create_edition(&run,&p).unwrap().events[0].analysis.is_none());assert_eq!(s.create_edition(&run,&p).unwrap().version,edition.version);}
