import { Button } from './components/ui/button.tsx';
import { Textarea } from './components/ui/textarea.tsx';
import { Feedback } from './components/ui/feedback.tsx';
import { AttachmentPreview } from './components/ui/attachment-preview.tsx';
import type { AgentQueueController } from './use-agent-queue.ts';
export function AgentQueuePanel({model:m,conversationKey,sessionId,onContinue}:{model:AgentQueueController;conversationKey:string;sessionId?:string;onContinue:()=>Promise<void>}){
  const entries=m.document.entries.filter(e=>e.conversationKey===conversationKey&&(!sessionId||e.sessionId===sessionId)),paused=m.document.paused[conversationKey],open=m.open[conversationKey]??true;
  if(!entries.length&&!m.error)return null;
  return <section className="agent-message-queue" aria-label="待发送消息"><header><Button variant="app-quiet" aria-expanded={open} onClick={()=>m.setOpen(before=>({...before,[conversationKey]:!open}))}>待发送 · {entries.length} {open?'⌃':'⌄'}</Button><span className="meta">{paused?'已暂停':'任务结束后按顺序发送'}</span>{paused&&<Button variant="app-quiet" disabled={m.busy} onClick={()=>void onContinue().catch(()=>{})}>继续队列</Button>}</header>{m.error&&<Feedback tone="error" role="alert">{m.error}</Feedback>}{open&&<ol>{entries.map(entry=>{const edit=m.edits[entry.id],editable=['waiting','editing'].includes(entry.status);return <li key={entry.id}><div className="agent-queue-heading"><span>{entry.behavior==='steer'?'补充当前任务':'排队'} · {entry.status==='nativeQueued'?'等待 Pi 接收消息':entry.status==='dispatching'?'正在交给 Pi':entry.status==='uncertain'?'需要核对':'待发送'}</span></div>{edit?<Textarea value={edit.payload.text} maxLength={100000} onChange={e=>m.update(entry.id,e.target.value)} aria-label="编辑这条排队消息"/>:<p>{entry.payload.text||'附加资料'}</p>}{!!entry.payload.images.length&&<div className="pi-image-list">{entry.payload.images.map(image=><AttachmentPreview key={image.id} value={{name:image.name,imageUrl:`data:${image.mimeType};base64,${image.data}`}}/>)}</div>}{entry.payload.files.map(file=><span className="meta" key={file.id}>{file.name} · </span>)}{!!entry.payload.objects.length&&<span className="meta">{entry.payload.objects.length} 个工作台对象</span>}{entry.error&&<Feedback tone="error">{entry.error}</Feedback>}<div className="agent-queue-actions">{edit?<><Button variant="app-quiet" disabled={m.busy||!editable} onClick={()=>void m.save(entry)}>保存编辑</Button><Button variant="app-quiet" disabled={m.busy} onClick={()=>void m.cancel(entry.id)}>取消编辑</Button></>:editable&&<Button variant="app-quiet" disabled={m.busy} onClick={()=>void m.edit(entry)}>编辑</Button>}{entry.status==='waiting'&&entry.behavior!=='steer'&&<Button variant="app-quiet" disabled={m.busy} onClick={()=>void m.change(entry,'steer')}>补充当前任务</Button>}{entry.status==='uncertain'&&<Button variant="app-quiet" disabled={m.busy} onClick={()=>void m.change(entry,'retry')}>确认未执行，重新排队</Button>}{(editable||entry.status==='uncertain')&&<Button variant="app-quiet" disabled={m.busy} onClick={()=>void m.change(entry,'remove')}>移除</Button>}</div></li>;})}</ol>}</section>;
}
