import type { NewsMaterial } from './news-contract.ts';
import {parseEvent} from './news-editorial-contract.ts';
import type { ModelChoice, NewsEvent } from './news-editorial-contract.ts';
export const pipelineStages = {prefilter:'相关性预筛',score:'独立评分',structure:'结构抽取',writing:'中文标题与导读',translation:'正文翻译',grouping:'事件关系与增量',digest:'事件概览',period:'周报 / 月报导读'} as const;
export interface SourceRule {sourceId:string;tier:'T1'|'T1_5'|'T2'|'EXCLUDE_MP';fetchBody:boolean;displayBody:boolean}
export interface PipelineConfig {models:Partial<Record<keyof typeof pipelineStages,ModelChoice>>;sources:SourceRule[];requestsPerMinute:number;requestsPerHour:number;requestsPerDay:number}
export const defaultPipeline = ():PipelineConfig => ({models:{},sources:[],requestsPerMinute:60,requestsPerHour:1000,requestsPerDay:5000});
export interface Article {legacyEventId?:string;id:string;material:NewsMaterial;titleZh:string;summaryZh:string;reason:string;category:string|null;tags:string[];subjects:string[];scope:string;fact:unknown;scoreFirst:number|null;scoreSecond:number|null;score:number|null;tier:string;selected:boolean;addsValue:boolean;selectionReason:string;occurrenceId:string;storyId:string;originalBody?:string;translatedBody?:string|null;translationComplete?:boolean;translationError?:string|null;bodyKind:string;bodyError:string|null;displayBody:boolean;status:string;processedAt:string;configRevision:number;upstream:string;bookmarked?:boolean}
export interface Brief {id:string;titleZh:string;summaryZh:string;sourceName:string;sourceId?:string;url?:string;publishedAt:string|null;category?:string|null;tags?:string[];score?:number|null;storyId?:string;occurrenceId:string;official?:boolean;selected?:boolean;related?:Brief[];sources?:number;followUp?:boolean;fillIn?:boolean}
export interface Story {id:string;title:string;digest:{title:string;digest:string}|null;heat:number;sources:number;latestAt:string|null;articles:Brief[]}
export interface ReaderEdition {id:string;kind:'daily'|'weekly'|'monthly';date:string;windowStart:string;windowEnd:string;generatedAt:string;overview:string;sections:Record<string,string>;main:Brief[];flashes:Brief[];gaps:string[];upstream:string}
export interface Receipt {id:number;runId:string;materialId:string;stage:string;model:string;promptHash:string;status:string;startedAt:string;finishedAt:string|null;usage:string|null;error:string|null;inputChars:number;responseChars:number|null}
export interface ReaderSnapshot {items:Article[];total:number;stories:Story[];editions:ReaderEdition[];taxonomy:{categories:{key:string;label:string;section:string;guide:string}[];topicTags:string[]};upstream:string}
export interface ArticleDetail {legacy?:NewsEvent|null;article:Article;bookmarked:boolean;position:number;related:Article[];steps:Receipt[]}
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw new Error('资讯阅读数据不完整，原记录保留。');return v as Record<string,unknown>;};
export function parsePipeline(value:unknown):PipelineConfig {if(value==null)return defaultPipeline();const v=object(value),models=object(v.models);const sources=v.sources;if(!Array.isArray(sources)||Object.entries(models).some(([key,m])=>{const choice=object(m);return !Object.hasOwn(pipelineStages,key)||typeof choice.provider!=='string'||typeof choice.id!=='string';})||sources.some(r=>{const s=object(r);return typeof s.sourceId!=='string'||!['T1','T1_5','T2','EXCLUDE_MP'].includes(String(s.tier))||typeof s.fetchBody!=='boolean'||typeof s.displayBody!=='boolean';})||['requestsPerMinute','requestsPerHour','requestsPerDay'].some(key=>!Number.isSafeInteger(v[key])||Number(v[key])<0||Number(v[key])>100000))throw new Error('资讯步骤配置不完整。');return v as unknown as PipelineConfig;}
export function parseReader(value:unknown):ReaderSnapshot {const v=object(value);if(!Array.isArray(v.items)||!Array.isArray(v.stories)||!Array.isArray(v.editions)||!Number.isSafeInteger(v.total)||!Array.isArray(object(v.taxonomy).categories))throw new Error('资讯阅读返回不完整，已有内容保留。');for(const a of v.items)parseArticle(a);return v as unknown as ReaderSnapshot;}
export function parseArticle(value:unknown):Article {const v=object(value),m=object(v.material);if(typeof v.id!=='string'||!/^[a-f0-9]{32}$/.test(v.id)||typeof v.titleZh!=='string'||typeof v.summaryZh!=='string'||!Array.isArray(v.tags)||typeof m.url!=='string'||typeof m.sourceName!=='string'||typeof v.storyId!=='string'||typeof v.selected!=='boolean'||typeof v.displayBody!=='boolean'||v.originalBody!=null&&(typeof v.originalBody!=='string'||v.originalBody.length>4*1024*1024)||v.translatedBody!=null&&(typeof v.translatedBody!=='string'||v.translatedBody.length>4*1024*1024))throw new Error('文章返回不完整，未显示部分正文。');return v as unknown as Article;}
export function parseDetail(value:unknown):ArticleDetail {const v=object(value);parseArticle(v.article);if(typeof v.bookmarked!=='boolean'||typeof v.position!=='number'||!Array.isArray(v.related)||!Array.isArray(v.steps))throw new Error('文章阅读状态不完整。');if(v.legacy!=null)v.legacy=parseEvent(v.legacy);return v as unknown as ArticleDetail;}
