import { domainLabels } from './news-contract.ts';
import type { EditorialController } from './use-news-editorial.ts';
import { equalEditorial } from './news-editorial-contract.ts';
import { EditorialFeedback } from './news-reading-panels.tsx';
import type { PiModel } from './pi-contract.ts';
export function NewsPreferences({ model, models = [] }: { model: EditorialController; models?: PiModel[] }) {
  const draft = model.draft; const config = draft?.config;
  if (!draft || !config) return <section className="news-page"><a href="#settings/news" className="foundation-link">← 返回资讯管理</a><EditorialFeedback model={model} /><button className="pill" disabled={model.loading} onClick={() => void model.refresh()}>读取资讯规则</button></section>;
  const dirty = !!model.snapshot && !equalEditorial(config, model.snapshot.preferences.config);
  const update = (patch: Partial<typeof config>) => model.changeConfig({ ...config, ...patch });
  return <section className="news-page"><div><a href="#settings/news" className="foundation-link">← 返回资讯管理</a><h2 className="title">领域、AI处理与运行</h2><p className="subtle">当前正式配置 v{model.snapshot?.preferences.revision} · {dirty ? '有未保存草稿' : '与正式配置一致'}。保存后下次任务生效；旧刊不重写，切页和切主题保留草稿。</p></div><EditorialFeedback model={model} />
    <form className="news-source-form news-rules-form" onSubmit={e => { e.preventDefault(); void model.save(); }}>
      <fieldset className="news-domain-fields"><legend>领域与筛选</legend>{config.domains.map((r, i) => <section className="news-rule" key={r.domain}><label className="choice"><input type="checkbox" checked={r.enabled} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, enabled: e.target.checked } : v) })} />{domainLabels[r.domain]}</label><label>范围与推荐规则<textarea aria-label={`${domainLabels[r.domain]}范围与推荐规则`} className="input" required maxLength={2000} value={r.rule} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, rule: e.target.value } : v) })} /></label><div className="news-rule-numbers"><label>日报最低相关性<input className="input" type="number" min={0} max={100} required value={r.minScore} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, minScore: e.target.valueAsNumber } : v) })} /></label><label>该领域每期最多条数<input className="input" type="number" min={0} max={5} required value={r.dailyLimit} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, dailyLimit: e.target.valueAsNumber } : v) })} /></label></div></section>)}</fieldset>
      <fieldset className="news-domain-fields"><legend>AI处理</legend><p className="meta">模型与认证复用本应用的 <a href="#settings" className="foundation-link">Pi模型设置</a>。这里不填写Key；留空使用本应用可用默认模型，未配置时资料保持待处理。推荐分是工作价值判断，不是可信概率。</p><label>本应用已加载的模型<select aria-label="资讯模型" className="select" value={config.model ? JSON.stringify([config.model.provider, config.model.id]) : ''} onChange={e => { if (!e.target.value) update({ model: null }); else { const [provider, id] = JSON.parse(e.target.value) as [string, string]; update({ model: { provider, id } }); } }}><option value="">使用本应用可用默认模型</option>{config.model && !models.some(m => m.provider === config.model!.provider && m.id === config.model!.id) && <option value={JSON.stringify([config.model.provider, config.model.id])}>当前指定：{config.model.provider} / {config.model.id}（运行时核对）</option>}{models.map(m => <option key={JSON.stringify([m.provider, m.id])} value={JSON.stringify([m.provider, m.id])}>{m.name} · {m.provider}</option>)}</select></label>{!models.length && <p className="meta">尚未加载模型列表；在Pi模型设置保存或连接后可选择。默认选项会在任务开始时核对实际可用模型。</p>}<details className="disclosure"><summary>高级：指定模型标识</summary><div className="news-rule-numbers"><label>模型提供商<input className="input" value={config.model?.provider ?? ''} maxLength={200} onChange={e => update({ model: { provider: e.target.value, id: config.model?.id ?? '' } })} /></label><label>模型ID<input className="input" value={config.model?.id ?? ''} maxLength={300} onChange={e => update({ model: { provider: config.model?.provider ?? '', id: e.target.value } })} /></label></div></details><div className="news-rule-numbers"><label>精选最低相关性<input className="input" type="number" min={0} max={100} required value={config.featuredScore} onChange={e => update({ featuredScore: e.target.valueAsNumber })} /></label><label>总览与首页最多条数<input className="input" type="number" min={0} max={3} required value={config.overviewLimit} onChange={e => update({ overviewLimit: e.target.valueAsNumber })} /></label></div><p className="meta">范围内未精选资讯仍能在全部动态查看；临界分、证据冲突或归组不明确时做一次复判，模型错误不盲重试。</p></fieldset>
      <fieldset className="news-domain-fields"><legend>采集与运行</legend><label className="choice"><input type="checkbox" checked={config.autoCollect} onChange={e => update({ autoCollect: e.target.checked })} />按信源频率自动采集</label><label className="choice"><input type="checkbox" checked={config.autoDaily} onChange={e => update({ autoDaily: e.target.checked })} />自动生成每日固定日报</label><label>日报时间（北京时间）<input className="input" type="time" required value={config.dailyTime} onChange={e => update({ dailyTime: e.target.value })} /></label><p className="meta">本应用实际运行时检查；当日时点后启动且未跑则补一次，不补多天。自动日报先采集再整理；暂停保留历史。关闭主窗口当前会退出，托盘运行等待后台模块接入。失败不自动再次调用付费模型，请在记录中手动重试。</p></fieldset>
      {model.pending && <p className="warn-t">上次保存回执待核对，草稿仍保留。可核对结果或重发同一个请求，不创建重复配置版本。</p>}
      {draft.revision !== model.snapshot?.preferences.revision && <p className="warn-t">正式配置已有更新，草稿基于 v{draft.revision}。<button type="button" className="text-action" disabled={!!model.pending} onClick={model.rebase}>保留草稿并对照最新版本</button></p>}
      <div className="form-actions"><button className="pill on" type="submit" disabled={!!model.busy || !model.connected}>{model.pending ? '重发上次保存请求' : '保存资讯配置'}</button>{model.pending && <button className="pill" type="button" disabled={!!model.busy} onClick={() => void model.reconcile()}>核对上次保存</button>}</div>
    </form>
  </section>;
}
