import { parseMaterialPage, domainLabels } from './news-contract.ts';
import type { Domain, NewsMaterial } from './news-contract.ts';
export interface ModelChoice { provider: string; id: string }
export interface DomainRule { domain: Domain; enabled: boolean; rule: string; minScore: number; dailyLimit: number }
export interface EditorialConfig { model: ModelChoice | null; domains: DomainRule[]; featuredScore: number; overviewLimit: number; autoCollect: boolean; autoDaily: boolean; dailyTime: string }
export interface Preferences { config: EditorialConfig; revision: number }
export interface CitedText { text: string; materialIds: string[] }
export interface EventDraft { eventKey: string; materialIds: string[]; domain: Domain | null; title: string; summary: string; facts: CitedText[]; score: number; reason: string; tags: string[]; limitations: string[]; needsReview: boolean; hasNewFacts: boolean }
export interface NewsEvent { id: string; revision: number; draft: EventDraft; materials: NewsMaterial[]; generatedAt: string; latestAt: string; configRevision: number; model: ModelChoice; promptVersion: number; featured: boolean; analysis: { generatedAt: string; model: ModelChoice; judgments: CitedText[]; limitations: string[] } | null }
export interface Edition { id: string; date: string; version: number; generatedAt: string; windowStart: string; windowEnd: string; configRevision: number; overviewIds: string[]; events: NewsEvent[]; incomplete: boolean; gaps: string[] }
export const editorialStatusLabels = { running: '正在整理', saving: '正在保存', completed: '已完成', failed: '整理失败', awaitingModel: '等待可用模型', interrupted: '整理中断', cancelled: '已取消' } as const;
export interface EditorialRun { id: string; kind: 'organize' | 'daily' | 'analysis'; eventId: string | null; status: keyof typeof editorialStatusLabels; startedAt: string; finishedAt: string | null; windowStart: string; windowEnd: string; configRevision: number; config: EditorialConfig; total: number; processed: number; error: string | null; scheduleDate: string | null }
export interface EditorialSnapshot { preferences: Preferences; events: NewsEvent[]; editions: Edition[]; runs: EditorialRun[]; pending: number; nextDailyAt: string | null }
export interface SavePreferences { requestId: string; expectedRevision: number; config: EditorialConfig }
export type ReadingTab = 'featured' | 'all' | 'hot' | 'daily';
function bad(): never { throw new Error('资讯整理返回的数据不完整，已有内容和草稿保留，请重新读取。'); }
function object(v: unknown): Record<string, unknown> { if (!v || typeof v !== 'object' || Array.isArray(v)) return bad(); return v as Record<string, unknown>; }
function text(v: unknown): string { if (typeof v !== 'string' || v.length > 10000) return bad(); return v; }
function number(v: unknown, min = 0, max = Number.MAX_SAFE_INTEGER): number { if (!Number.isSafeInteger(v) || Number(v) < min || Number(v) > max) return bad(); return v as number; }
function bool(v: unknown): boolean { if (typeof v !== 'boolean') return bad(); return v; }
function list<T>(v: unknown, parse: (v: unknown) => T): T[] { if (!Array.isArray(v)) return bad(); return v.map(parse); }
function time(v: unknown): string { const t = text(v); return Number.isFinite(Date.parse(t)) ? t : bad(); }
function domain(v: unknown): Domain { return typeof v === 'string' && Object.hasOwn(domainLabels, v) ? v as Domain : bad(); }
function model(v: unknown): ModelChoice { const m = object(v); return { provider: text(m.provider), id: text(m.id) }; }
export function parseConfig(v: unknown): EditorialConfig { const c = object(v); const domains = list(c.domains, value => { const r = object(value); return { domain: domain(r.domain), enabled: bool(r.enabled), rule: text(r.rule), minScore: number(r.minScore, 0, 100), dailyLimit: number(r.dailyLimit, 0, 5) }; });
  if (domains.length !== 3 || new Set(domains.map(r => r.domain)).size !== 3 || !/^([01]\d|2[0-3]):[0-5]\d$/.test(text(c.dailyTime))) return bad();
  return { model: c.model === null ? null : model(c.model), domains, featuredScore: number(c.featuredScore, 0, 100), overviewLimit: number(c.overviewLimit, 0, 3), autoCollect: bool(c.autoCollect), autoDaily: bool(c.autoDaily), dailyTime: text(c.dailyTime) }; }
export function parsePreferences(v: unknown): Preferences { const p = object(v); return { config: parseConfig(p.config), revision: number(p.revision, 1) }; }
function cited(v: unknown): CitedText { const f = object(v); return { text: text(f.text), materialIds: list(f.materialIds, text) }; }
export function parseEvent(v: unknown): NewsEvent { const e = object(v); const d = object(e.draft); const materials = parseMaterialPage({ items: e.materials, total: Array.isArray(e.materials) ? e.materials.length : 0, page: 0, pageSize: Array.isArray(e.materials) ? Math.max(1, e.materials.length) : 1 }).items;
  const draft: EventDraft = { eventKey: text(d.eventKey), materialIds: list(d.materialIds, text), domain: d.domain === null ? null : domain(d.domain), title: text(d.title), summary: text(d.summary), facts: list(d.facts, cited), score: number(d.score, 0, 100), reason: text(d.reason), tags: list(d.tags, text), limitations: list(d.limitations, text), needsReview: bool(d.needsReview), hasNewFacts: bool(d.hasNewFacts) };
  if (!/^[a-f0-9]{64}$/.test(text(e.id)) || draft.materialIds.some(id => !materials.some(m => m.id === id)) || draft.facts.some(f => f.materialIds.some(id => !draft.materialIds.includes(id)))) return bad();
  const a = e.analysis === null ? null : object(e.analysis); const analysis = a && { generatedAt: time(a.generatedAt), model: model(a.model), judgments: list(a.judgments, cited), limitations: list(a.limitations, text) };
  if (analysis?.judgments.some(f => f.materialIds.some(id => !draft.materialIds.includes(id)))) return bad();
  return { id: text(e.id), revision: number(e.revision, 1), draft, materials, generatedAt: time(e.generatedAt), latestAt: time(e.latestAt), configRevision: number(e.configRevision, 1), model: model(e.model), promptVersion: number(e.promptVersion, 1), featured: bool(e.featured), analysis }; }
function edition(v: unknown): Edition { const e = object(v); const events = list(e.events, parseEvent); const overviewIds = list(e.overviewIds, text); if (overviewIds.some(id => !events.some(e => e.id === id))) return bad(); return { id: text(e.id), date: text(e.date), version: number(e.version, 1), generatedAt: time(e.generatedAt), windowStart: time(e.windowStart), windowEnd: time(e.windowEnd), configRevision: number(e.configRevision, 1), overviewIds, events, incomplete: bool(e.incomplete), gaps: list(e.gaps, text) }; }
export function parseEditorialSnapshot(v: unknown): EditorialSnapshot { const s = object(v); const runs = list(s.runs, value => { const r = object(value); const status = text(r.status); if (!(Object.hasOwn(editorialStatusLabels, status)) || !['daily', 'organize', 'analysis'].includes(text(r.kind))) return bad(); return { id: text(r.id), kind: r.kind as EditorialRun['kind'], eventId: r.eventId == null ? null : text(r.eventId), status: status as EditorialRun['status'], startedAt: time(r.startedAt), finishedAt: r.finishedAt === null ? null : time(r.finishedAt), windowStart: time(r.windowStart), windowEnd: time(r.windowEnd), configRevision: number(r.configRevision, 1), config: parseConfig(r.config), total: number(r.total), processed: number(r.processed), error: r.error === null ? null : text(r.error), scheduleDate: r.scheduleDate === null ? null : text(r.scheduleDate) }; }); return { preferences: parsePreferences(s.preferences), events: list(s.events, parseEvent), editions: list(s.editions, edition), runs, pending: number(s.pending), nextDailyAt: s.nextDailyAt === null ? null : time(s.nextDailyAt) }; }
export function independentSources(event: NewsEvent): number { return new Set(event.materials.map(m => m.sourceId)).size; }
export function readingEvents(events: NewsEvent[], tab: ReadingTab, selected: Domain | ''): NewsEvent[] { return events.filter(e => (!selected || e.draft.domain === selected) && (tab !== 'featured' || e.featured) && (tab !== 'hot' || independentSources(e) >= 2)).sort((a, b) => tab === 'hot' ? independentSources(b) - independentSources(a) || Date.parse(b.latestAt) - Date.parse(a.latestAt) : Date.parse(b.latestAt) - Date.parse(a.latestAt)); }
export function equalEditorial(a: EditorialConfig, b: EditorialConfig): boolean { return JSON.stringify(a) === JSON.stringify(b); }
