import { parseMaterialPage } from './news-contract.ts';
import type { NewsMaterial } from './news-contract.ts';
import { parseConfig } from './news-editorial-contract.ts';
import type { EditorialConfig, ModelChoice } from './news-editorial-contract.ts';
export const processingPhases:Record<string,string>={preparing:'准备本批资料',connecting:'启动资讯专用 Pi',checkingModel:'核对可用模型',thinking:'模型正在推理',usingSavedResult:'复用已留存结果',alreadyProcessed:'本批已处理，跳过模型调用',sending:'提交模型请求',waitingModel:'等待模型返回',receiving:'接收模型返回文本',readingResult:'读取完整返回',validating:'校验格式、范围与出处',reviewing:'准备复判',saving:'保存本批结果',buildingEdition:'生成固定刊期',completed:'已完成',cancelled:'已取消',failed:'处理失败',awaitingModel:'等待可用模型',interrupted:'已中断'};
export interface ProcessingProgress {runId:string;phase:string;startedAt:string;updatedAt:string;batch:number;batches:number;batchSize:number;completed:number;total:number;pid:number|null;model:ModelChoice|null;input:NewsMaterial[];response:string;receivedChars:number;steps:{at:string;phase:string}[];error:string|null}
export interface TaskDetail {runId:string;batch:number;batches:number;batchSize:number;configRevision:number;rules:EditorialConfig;input:NewsMaterial[];outputs:{name:string;text:string;truncated:boolean}[];result:unknown;progress:ProcessingProgress|null}
const bad=()=>new Error('处理记录格式不完整，原记录保留。');
const object=(v:unknown):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v))throw bad();return v as Record<string,unknown>;};
const text=(v:unknown):string=>{if(typeof v!=='string')throw bad();return v;};
const number=(v:unknown):number=>{if(typeof v!=='number'||!Number.isSafeInteger(v)||v<0)throw bad();return v;};
const list=(v:unknown):unknown[]=>{if(!Array.isArray(v))throw bad();return v;};
export function parsePendingPage(value:unknown){const v=object(value);return {page:parseMaterialPage(v.page),dailyTotal:number(v.dailyTotal),at:text(v.at)};}
function materials(v:unknown){const rows=list(v);return parseMaterialPage({items:rows,total:rows.length,page:0,pageSize:Math.max(1,rows.length)}).items;}
export function parseProgress(value:unknown):ProcessingProgress|null{if(value===null)return null;const v=object(value),m=v.model===null?null:object(v.model);return {runId:text(v.runId),phase:text(v.phase),startedAt:text(v.startedAt),updatedAt:text(v.updatedAt),batch:number(v.batch),batches:number(v.batches),batchSize:number(v.batchSize),completed:number(v.completed),total:number(v.total),pid:v.pid===null?null:number(v.pid),model:m?{provider:text(m.provider),id:text(m.id)}:null,input:materials(v.input),response:text(v.response),receivedChars:number(v.receivedChars),steps:list(v.steps).map(item=>{const row=object(item);return {at:text(row.at),phase:text(row.phase)};}),error:v.error===null?null:text(v.error)};}
export function parseTaskDetail(value:unknown):TaskDetail{const v=object(value);return {runId:text(v.runId),batch:number(v.batch),batches:number(v.batches),batchSize:number(v.batchSize),configRevision:number(v.configRevision),rules:parseConfig(v.rules),input:materials(v.input),outputs:list(v.outputs).map(item=>{const row=object(item);if(typeof row.truncated!=='boolean')throw bad();return {name:text(row.name),text:text(row.text),truncated:row.truncated};}),result:v.result??null,progress:parseProgress(v.progress)};}
