import {useEffect,useState} from 'react';
import type {ReactNode} from 'react';
import {invoke,isTauri} from './desktop-api.ts';
import {Button} from './components/ui/button.tsx';
import {UILink} from './components/ui/ui-link.tsx';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogClose} from './components/ui/dialog.tsx';
import type {NewsController} from './use-news.ts';
export function sourceUrl(value:string):string|null {try{const u=new URL(value);return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password&&u.hostname.includes('.')&&!/^(localhost|127\.|10\.|192\.168\.|169\.254\.|0\.)/.test(u.hostname)&&!u.hostname.endsWith('.local')?u.href:null;}catch{return null;}}
export function ReaderLink({href,news,children}:{href:string;news:NewsController;children:ReactNode}){const url=sourceUrl(href);return url?<UILink variant="text" href={url} target="_blank" rel="noopener noreferrer" onClick={e=>{if(news.connected){e.preventDefault();void news.openOriginal(url);}}}>{children}</UILink>:<span>{children}</span>;}
interface Block {kind:'heading'|'paragraph'|'code'|'list'|'quote'|'table'|'image'|'rule';text:string;depth?:number;index:number}
export function bodyBlocks(body:string):Block[]{const lines=body.split('\n'),blocks:Block[]=[];let i=0;while(i<lines.length){const line=lines[i].trim();if(!line){i++;continue;}const index=blocks.length;if(line.startsWith('```')){const buffer:string[]=[];i++;while(i<lines.length&&!lines[i].trim().startsWith('```'))buffer.push(lines[i++]);if(i<lines.length)i++;blocks.push({kind:'code',text:buffer.join('\n'),index});continue;}const heading=/^(#{1,6})\s+(.+)$/.exec(line);if(heading){blocks.push({kind:'heading',text:heading[2],depth:Math.min(heading[1].length+1,6),index});i++;continue;}if(/^!\[.*\]\(.*\)$/.test(line)){blocks.push({kind:'image',text:line,index});i++;continue;}if(/^(---+|\*\*\*+)$/.test(line)){blocks.push({kind:'rule',text:'',index});i++;continue;}let kind:Block['kind']=/^[-*]\s|^\d+[.)]\s/.test(line)?'list':line.startsWith('>')?'quote':line.startsWith('|')?'table':'paragraph';const buffer=[line];i++;while(i<lines.length&&lines[i].trim()&&!/^(#{1,6}\s|```|!\[)/.test(lines[i].trim())){const next=lines[i].trim();if(kind==='list'&&!/^[-*]\s|^\d+[.)]\s/.test(next)||kind==='quote'&&!next.startsWith('>')||kind==='table'&&!next.startsWith('|')||kind==='paragraph'&&/^[-*]\s|^\d+[.)]\s|^>|^\|/.test(next))break;buffer.push(next);i++;}blocks.push({kind,text:buffer.join('\n'),index});}return blocks;}
export function bodyHeadings(body:string){return bodyBlocks(body).filter(b=>b.kind==='heading').map(b=>({id:`reader-heading-${b.index}`,text:b.text,depth:b.depth??2}));}
function inline(text:string,news:NewsController):ReactNode[]{const result:ReactNode[]=[];const token=/(\[[^\]\n]+\]\(https?:\/\/[^\s)]+\)|\*\*[^*\n]+\*\*|`[^`\n]+`|\*[^*\n]+\*)/g;let start=0;for(const match of text.matchAll(token)){if(match.index>start)result.push(text.slice(start,match.index));const value=match[0],key=`${match.index}-${result.length}`;const link=/^\[([^\]]+)\]\((.+)\)$/.exec(value);if(link)result.push(<ReaderLink key={key} href={link[2]} news={news}>{link[1]}</ReaderLink>);else if(value.startsWith('**'))result.push(<strong key={key}>{value.slice(2,-2)}</strong>);else if(value.startsWith('`'))result.push(<code key={key}>{value.slice(1,-1)}</code>);else result.push(<em key={key}>{value.slice(1,-1)}</em>);start=match.index+value.length;}if(start<text.length)result.push(text.slice(start));return result;}
function Code({text}:{text:string}){const [notice,setNotice]=useState('');return <div className="reader-code"><Button variant="app-text" className="reader-code-copy" onClick={()=>{void navigator.clipboard.writeText(text).then(()=>setNotice('已复制')).catch(()=>setNotice('剪贴板受限，请手动选择复制'));}}>{notice||'复制代码'}</Button><pre tabIndex={0}><code>{text}</code></pre></div>;}
function Picture({text,news}:{text:string;news:NewsController}){const match=/^!\[(.*)\]\((.*)\)$/.exec(text),[url,setUrl]=useState(''),[error,setError]=useState(''),[expanded,setExpanded]=useState(false);const remote=match?sourceUrl(match[2]):null;
  useEffect(()=>{if(!remote||!isTauri())return;let disposed=false,blob='';void invoke<{mime:string;bytes:number[]}>('news_reader_image',{url:remote}).then(v=>{if(disposed)return;blob=URL.createObjectURL(new Blob([new Uint8Array(v.bytes)],{type:v.mime}));setUrl(blob);}).catch(()=>{if(!disposed)setError('图片暂时无法读取');});return()=>{disposed=true;if(blob)URL.revokeObjectURL(blob);};},[remote]);
  if(!match)return null;return <figure className="reader-image">{url?<Dialog open={expanded} onOpenChange={setExpanded}><DialogTrigger asChild><Button variant="ghost" className="reader-image-trigger" aria-label={`放大图片：${match[1]||'正文配图'}`}><img src={url} alt={match[1]} /></Button></DialogTrigger><DialogContent className="reader-lightbox" showCloseButton={false} aria-describedby={undefined}><DialogTitle className="sr-only">{match[1]||'正文图片'}</DialogTitle><DialogClose asChild><Button variant="app-pill">关闭图片</Button></DialogClose><img src={url} alt={match[1]} /></DialogContent></Dialog>:<ReaderLink href={match[2]} news={news}>{error||'正在读取图片…'}</ReaderLink>}{match[1]&&<figcaption>{match[1]}</figcaption>}</figure>;
}
export function ArticleBody({body,news}:{body:string;news:NewsController}){return <div className="reader-rich-body">{bodyBlocks(body).map(block=>{const key=block.index;switch(block.kind){case 'heading':{const Tag=`h${block.depth}` as 'h2'|'h3'|'h4'|'h5'|'h6';return <Tag id={`reader-heading-${key}`} key={key}>{inline(block.text,news)}</Tag>;}case 'code':return <Code key={key} text={block.text}/>;case 'image':return <Picture key={key} text={block.text} news={news}/>;case 'list':{const ordered=/^\d+[.)]/.test(block.text);const rows=block.text.split('\n').map((line,i)=><li key={i}>{inline(line.replace(/^([-*]|\d+[.)])\s+/,''),news)}</li>);return ordered?<ol key={key}>{rows}</ol>:<ul key={key}>{rows}</ul>;}case 'quote':return <blockquote key={key}>{inline(block.text.replace(/^>\s?/gm,''),news)}</blockquote>;case 'table':{const rows=block.text.split('\n').filter(line=>!/^\|?\s*:?-+/.test(line)).map(line=>line.replace(/^\||\|$/g,'').split('|').map(v=>v.trim()));return <div className="reader-table" key={key} tabIndex={0}><table><thead><tr>{rows[0]?.map((cell,i)=><th key={i}>{inline(cell,news)}</th>)}</tr></thead><tbody>{rows.slice(1).map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{inline(cell,news)}</td>)}</tr>)}</tbody></table></div>;}case 'rule':return <hr key={key}/>;default:return <p key={key}>{inline(block.text,news)}</p>;}})}</div>;}
