import { EmptyState } from './components/ui/empty-state.tsx';
import {LoadingStatus} from './components/ui/loading-status.tsx';
import { Feedback } from './components/ui/feedback.tsx';
import { UILink } from './components/ui/ui-link.tsx';
import { StatusBadge } from './components/ui/status-badge.tsx';
import { Disclosure } from './components/ui/disclosure.tsx';
import { Button } from './components/ui/button.tsx';
import { NativeSelect } from './components/ui/native-select.tsx';
import { Textarea } from './components/ui/textarea.tsx';
import { useEffect, useState } from 'react';
import { domainLabels, formatNewsTime, publicationLabel } from './news-contract.ts';
import type { NewsController } from './use-news.ts';
import type { EditorialController } from './use-news-editorial.ts';
import { independentSources, readingEvents } from './news-editorial-contract.ts';
import type { NewsEvent, CitedText, Edition } from './news-editorial-contract.ts';
import { workspaceError } from './workspace-contract.ts';
export function EditorialFeedback({ model, controls = true }: { model: EditorialController; controls?: boolean }) { return <div className="news-feedback" aria-live="polite">
  {model.loadError && <Feedback as="p" tone="error" className="form-error" role="alert">{model.loadError}</Feedback>}{model.error && <Feedback as="p" tone="error" className="form-error" role="alert">{model.error}</Feedback>}
  <LoadingStatus className="news-task-status" active={model.loading || model.active}>{model.active ? <><span>资讯任务正在运行，使用开始时的规则。</span>{controls && <Button variant="app-text" className="text-action" onClick={() => void model.cancel()}>取消资讯整理 / 分析</Button>}</> : '正在读取资讯，已有内容保留…'}</LoadingStatus></div>; }
function ReadingFeedback({ model }: { model: EditorialController }) { return <div className="news-feedback" aria-live="polite">{model.loadError && <Feedback as="p" tone="error" className="form-error" role="alert">{model.loadError}</Feedback>}<LoadingStatus active={model.loading}>正在读取资讯，已有内容保留…</LoadingStatus></div>; }
function SourceLink({ url, news, children }: { url: string; news: NewsController; children: React.ReactNode }) { return <UILink variant="text" className="foundation-link" href={url} target="_blank" rel="noopener noreferrer" onClick={event => { if (news.connected) { event.preventDefault(); void news.openOriginal(url); } }}>{children}</UILink>; }
function Related({ event, news }: { event: NewsEvent; news: NewsController }) { return <ol className="news-related">{event.materials.map(m => <li key={m.id} id={`material-${m.id}`}><SourceLink news={news} url={m.url}>{m.sourceName} · {m.title}</SourceLink><p className="meta">原发布时间：{publicationLabel(m)} · 发现 {formatNewsTime(m.discoveredAt)}</p><p className="news-url meta">{m.url}</p></li>)}</ol>; }
function Citations({ fact, event, news }: { fact: CitedText; event: NewsEvent; news: NewsController }) { return <li><p>{fact.text}</p><div className="meta">出处：{fact.materialIds.map(id => { const m = event.materials.find(m => m.id === id); return m && <span key={id}><SourceLink news={news} url={m.url}>{m.sourceName}</SourceLink>　</span>; })}</div></li>; }
export function NewsReading({ model, news }: { model: EditorialController; news: NewsController }) {
  const events = readingEvents(model.snapshot?.events ?? [], model.tab, model.domain); const visible = events.slice(0, model.limit);
  return <section className="news-page news-reading">
    <div className="news-reading-controls">
      <nav className="news-reading-navigation" aria-label="阅读分类">{([['featured', '精选'], ['all', '全部动态'], ['hot', '热点'], ['daily', '日报']] as const).map(([tab, label]) => <Button variant="app-reading-tab" key={tab} className="news-reading-tab" aria-pressed={model.tab === tab} onClick={() => { model.setTab(tab); model.setLimit(50); }}>{label}</Button>)}</nav>
      {model.tab !== 'daily' && <div className="news-domain-tabs" role="group" aria-label="资讯领域"><span className="news-filter-label">领域</span><Button variant="app-domain" className="news-domain-option" aria-pressed={!model.domain} onClick={() => { model.setDomain(''); model.setLimit(50); }}>全部领域</Button>{Object.entries(domainLabels).map(([domain, label]) => <Button variant="app-domain" key={domain} className="news-domain-option" aria-pressed={model.domain === domain} onClick={() => { model.setDomain(domain as keyof typeof domainLabels); model.setLimit(50); }}>{label}</Button>)}</div>}
    </div>
    <ReadingFeedback model={model} />
    {model.tab === 'daily' ? <EditionPanel model={model} /> : <>
      <div className="news-reading-caption"><p className="meta">{model.domain ? domainLabels[model.domain] : '全部领域'} · {events.length} 个已整理事件</p><span className="meta">中文导读 · AI判断 · 保留出处</span></div>
      {model.tab === 'hot' && <p className="meta">热点依据本站订阅来源数，不代表全网热度或事实核验。</p>}
      {!events.length ? <EmptyState as="div" className="foundation-empty"><h3>{model.tab === 'hot' ? '还没有多来源热点' : model.tab === 'featured' ? '还没有符合规则的精选' : '还没有已整理资讯'}</h3><p>这里只展示已整理的内容和出处。你可以切换阅读分类，查看已有结果。</p><div className="form-actions"><Button variant="app-text" className="text-action" onClick={() => { model.setTab('all'); model.setDomain(''); }}>查看全部动态</Button></div></EmptyState> : <ol className="news-materials">{visible.map(event => <li className="news-material" key={event.id}><div className="news-time-rail"><time dateTime={event.latestAt}>{formatNewsTime(event.latestAt)}</time><span>事件最新资料</span></div><article className="news-entry"><div className="news-entry-source"><span>{event.materials[0]?.sourceName} · {independentSources(event)} 个订阅来源</span><StatusBadge className="news-status">{event.draft.domain && domainLabels[event.draft.domain]}</StatusBadge></div><h3 className="news-entry-title"><UILink variant="plain" href={`#news/events/${event.id}`}>{event.draft.title}</UILink></h3><p className="news-summary">{event.draft.summary}</p><div className="news-recommendation"><span className="news-score">AI 推荐 {event.draft.score}/100</span><p className="news-reason" title={event.draft.reason}>{event.draft.reason}</p></div>{event.materials.length > 1 && <Disclosure className="disclosure"><summary>{event.materials.length} 条相关报道 / 进展</summary><Related event={event} news={news} /></Disclosure>}<div className="news-tags">{event.draft.tags.map(tag => <StatusBadge key={tag} className="news-status">{tag}</StatusBadge>)}</div></article></li>)}</ol>}
      {visible.length < events.length && <Button variant="app-pill" className="pill" onClick={() => model.setLimit(model.limit + 50)}>继续显示50个事件</Button>}
    </>}
  </section>;
}
export function NewsEventPage({ id, model, news }: { id: string; model: EditorialController; news: NewsController }) {
  const event = model.snapshot?.events.find(e => e.id === id); const [original, setOriginal] = useState(false);
  if (!event) return <section className="news-page"><UILink variant="text" href="#news" className="foundation-link">← 返回资讯</UILink><ReadingFeedback model={model} /><EmptyState as="div" className="foundation-empty"><h2>{model.loading ? '正在读取事件' : '未找到这个事件'}</h2><p>请重新读取核对；不会补写虚构内容。</p><Button variant="app-pill" className="pill" onClick={() => void model.refresh()}>重新读取</Button></EmptyState></section>;
  return <section className="news-page"><UILink variant="text" className="foundation-link" href="#news">← 返回资讯（保留筛选）</UILink><ReadingFeedback model={model} /><div className="news-article-layout">
    <aside className="news-article-meta"><Disclosure open className="disclosure"><summary>来源与阅读目录</summary><p>{event.materials[0]?.sourceName} · {independentSources(event)} 个来源</p><p className="meta">资料最新时间：{formatNewsTime(event.latestAt)}</p><p className="meta">整理：{formatNewsTime(event.generatedAt)} · 事件 v{event.revision}</p><nav aria-label="文章目录">{[['guide', 'AI导读'], ['facts', '来源事实'], ['body', '可用摘要'], ['analysis', '事件分析'], ['sources', '相关报道与进展']].map(([target, label]) => <Button variant="app-text" key={target} className="text-action" onClick={() => document.getElementById(`news-${target}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>{label}</Button>)}</nav></Disclosure></aside>
    <article className="news-article"><h2>{event.draft.title}</h2><section id="news-guide"><h3>AI导读</h3><p>{event.draft.summary}</p><p className="meta">模型 {event.model.provider} / {event.model.id} · 规则 v{event.configRevision} · 只依据已列订阅摘要</p></section><section id="news-facts"><h3>来源事实</h3><ul className="news-facts">{event.draft.facts.map((fact, i) => <Citations key={i} fact={fact} event={event} news={news} />)}</ul></section><section id="news-body"><h3>可用摘要</h3><div className="news-reading-tabs"><Button variant="app-pill" className="pill" aria-pressed={!original} onClick={() => setOriginal(false)}>中文整理</Button><Button variant="app-pill" className="pill" aria-pressed={original} onClick={() => setOriginal(true)}>订阅原文</Button></div><p className="meta">未取得许可正文，仅提供订阅摘要与原文链接；AI没有补写全文。</p>{original ? event.materials.map(m => <div className="news-original" key={m.id}><h4>{m.title}</h4><p className="meta">{m.sourceName} · 原发布时间：{publicationLabel(m)}</p><p>{m.summary || '订阅未提供摘要。'}{m.summaryTruncated && '（摘要节选）'}</p><SourceLink news={news} url={m.url}>打开来源原文 ↗</SourceLink></div>) : <><p>{event.draft.summary}</p><p className="meta">中文内容为AI依据摘要的整理，不是原文全文翻译。</p></>}</section><section id="news-analysis"><h3>事件分析 · AI判断</h3>{event.analysis ? <><ul className="news-facts">{event.analysis.judgments.map((fact, i) => <Citations key={i} fact={fact} event={event} news={news} />)}</ul><h4>未验证项与限制</h4><ul>{event.analysis.limitations.map((t, i) => <li key={i}>{t}</li>)}</ul><p className="meta">{formatNewsTime(event.analysis.generatedAt)} · {event.analysis.model.provider} / {event.analysis.model.id}</p></> : <p className="subtle">暂无已保存的事件分析。</p>}</section><section id="news-sources"><h3>相关报道与进展</h3><Related event={event} news={news} /></section></article>
    <aside className="news-article-notes"><h3>推荐理由 · AI判断</h3><p className="news-reason">{event.draft.reason}</p><p className="meta">相关性 {event.draft.score}/100，不是可信概率。</p><h3>证据限制</h3><ul>{event.draft.limitations.map((t, i) => <li key={i}>{t}</li>)}</ul>{independentSources(event) === 1 && <p className="meta">只有一个订阅来源，不构成多方核验。</p>}<h3>主题标签</h3><div className="news-tags">{event.draft.tags.map(t => <StatusBadge key={t} className="news-status">{t}</StatusBadge>)}</div><h3>材料</h3><Related event={event} news={news} /></aside>
  </div></section>;
}
export function EditionPanel({ model }: { model: EditorialController }) {
  const editions = model.snapshot?.editions ?? []; const edition = editions.find(e => e.id === model.editionId) ?? editions[0];
  const [texts, setTexts] = useState<Record<string, string>>({}); const [failure, setFailure] = useState('');
  useEffect(() => { if (!edition || texts[edition.id] || !model.connected) return; let disposed = false; const id = edition.id; void model.readEditionText(id).then(text => { if (!disposed) { setTexts(p => ({ ...p, [id]: text })); setFailure(''); } }).catch(e => { if (!disposed) setFailure(workspaceError(e)); }); return () => { disposed = true; }; }, [edition?.id, model.connected, texts]);
  return <section className="news-edition"><div className="news-toolbar"><div><h2 className="title">固定日报</h2><p className="subtle">整期显示、复制与A4 PDF来自同一刊期，不受上方领域筛选影响。</p></div></div>
    {!edition ? <EmptyState as="div" className="foundation-empty"><h3>还没有固定刊期</h3><p>依据过去24小时的已整理内容成刊；空刊不凑数，失败不冒充成功。</p></EmptyState> : <><label className="news-edition-select">选择完整刊期<NativeSelect variant="app" className="select" value={edition.id} onChange={e => model.setEditionId(e.target.value)}>{editions.map(e => <option key={e.id} value={e.id}>{e.date} · v{e.version} · {formatNewsTime(e.generatedAt)}{e.incomplete ? '（覆盖不完整）' : ''}</option>)}</NativeSelect></label><div className="form-actions"><Button variant="app-pill" className="pill" disabled={!!model.busy || !model.connected} onClick={() => void model.copy(edition.id)}>复制整期</Button><Button variant="app-pill" className="pill" disabled={!!model.busy || !model.connected} onClick={() => void model.exportPdf(edition.id)}>导出A4 PDF</Button></div>{failure && <Feedback as="p" tone="error" className="form-error" role="alert">{failure}</Feedback>}{model.readingError && <Feedback as="p" tone="error" className="form-error" role="alert">{model.readingError}</Feedback>}<EditionDocument edition={edition} text={texts[edition.id]} />{model.copyText && model.copyEditionId === edition.id && <label>手选完整刊期<Textarea variant="inline" className="input news-copy-text" readOnly value={model.copyText} onFocus={e => e.target.select()} /></label>}</>}
  </section>;
}
function EditionDocument({ edition, text }: { edition: Edition; text?: string }) { return <article className="news-edition-document" aria-label={`${edition.date} 日报 v${edition.version}`}>{text ? <pre>{text}</pre> : <p className="meta" role="status">正在读取完整刊期文本…</p>}</article>; }
