import { useEffect, useState } from 'react';
import { invoke } from '@tauri-apps/api/core';
import { domainLabels, formatNewsTime, publicationLabel } from './news-contract.ts';
import type { NewsController } from './use-news.ts';
import type { EditorialController } from './use-news-editorial.ts';
import { editorialStatusLabels, independentSources, readingEvents } from './news-editorial-contract.ts';
import type { NewsEvent, CitedText, Edition } from './news-editorial-contract.ts';
import { workspaceError } from './workspace-contract.ts';
export function EditorialFeedback({ model }: { model: EditorialController }) { return <div className="news-feedback" aria-live="polite">
  {model.loadError && <p className="form-error" role="alert">{model.loadError}</p>}{model.error && <p className="form-error" role="alert">{model.error}</p>}{model.notice && <p className="subtle" role="status">{model.notice}</p>}
  {model.loading && <p className="meta" role="status">正在读取资讯，已有内容保留…</p>}{model.active && <p className="meta" role="status">资讯任务正在运行，使用开始时的规则。<button className="text-action" onClick={() => void model.cancel()}>取消资讯整理 / 分析</button></p>}</div>; }
export function NewsRuns({ model }: { model: EditorialController }) { return <section className="news-run-section"><h2 className="title">资讯整理与日报记录</h2><p className="meta">过去24小时的处理进度；已完成批次不重复付费调用。失败需手动重试。<br/>自动日报下次时间：{formatNewsTime(model.snapshot?.nextDailyAt ?? null)}（北京时间）</p>
  <ul className="news-runs">{model.snapshot?.runs.map(run => <li className="news-run" key={run.id}><div className="news-run-main"><strong>{run.kind === 'daily' ? '日报' : run.kind === 'analysis' ? '事件分析' : '整理'}{run.scheduleDate && ' · 定时'}</strong><span className="news-status">{editorialStatusLabels[run.status]}</span><span className="meta">{formatNewsTime(run.startedAt)} · 规则 v{run.configRevision}</span></div><p className="meta">处理 {run.processed} / {run.total} 条 · 窗口 {formatNewsTime(run.windowStart)} — {formatNewsTime(run.windowEnd)}</p>{run.error && <p className="form-error">{run.error}</p>}{['failed', 'awaitingModel', 'cancelled', 'interrupted'].includes(run.status) && <button className="text-action" disabled={!!model.busy || model.active} onClick={() => void model.organize(run.kind, run.id)}>重试未完成部分（保留输入与已保存结果）</button>}</li>)}</ul>{!model.snapshot?.runs.length && <p className="subtle">暂无整理任务记录。</p>}</section>; }
function SourceLink({ url, news, children }: { url: string; news: NewsController; children: React.ReactNode }) { return <a className="foundation-link" href={url} target="_blank" rel="noopener noreferrer" onClick={event => { if (news.connected) { event.preventDefault(); void news.openOriginal(url); } }}>{children}</a>; }
function Related({ event, news }: { event: NewsEvent; news: NewsController }) { return <ol className="news-related">{event.materials.map(m => <li key={m.id} id={`material-${m.id}`}><SourceLink news={news} url={m.url}>{m.sourceName} · {m.title}</SourceLink><p className="meta">原发布时间：{publicationLabel(m)} · 发现 {formatNewsTime(m.discoveredAt)}</p><p className="news-url meta">{m.url}</p></li>)}</ol>; }
function Citations({ fact, event, news }: { fact: CitedText; event: NewsEvent; news: NewsController }) { return <li><p>{fact.text}</p><div className="meta">出处：{fact.materialIds.map(id => { const m = event.materials.find(m => m.id === id); return m && <span key={id}><SourceLink news={news} url={m.url}>{m.sourceName}</SourceLink>　</span>; })}</div></li>; }
export function NewsReading({ model, news }: { model: EditorialController; news: NewsController }) {
  const events = readingEvents(model.snapshot?.events ?? [], model.tab, model.domain); const visible = events.slice(0, model.limit);
  return <section className="news-page news-reading"><div className="news-toolbar"><div><p className="subtle">中文导读与出处一起保存，评分是AI推荐判断。</p></div><div className="form-actions"><a className="pill" href="#news/materials">采集资料</a><a className="pill" href="#settings/news">资讯管理</a><button className="pill" disabled={!news.connected || news.collecting} onClick={() => void news.collect()}>{news.collecting ? '正在采集…' : '手动采集'}</button><button className="pill on" disabled={!model.connected || !!model.busy || model.active} onClick={() => void model.organize('organize')}>整理待处理资料</button></div></div>
    <EditorialFeedback model={model} />{news.collecting && <button className="text-action" onClick={() => void news.cancelCapture()}>取消采集（保留已取得输入）</button>}{news.error && <p className="form-error" role="alert">{news.error}</p>}{news.notice && <p className="subtle">{news.notice}</p>}
    <div className="news-reading-tabs" aria-label="阅读入口">{([['featured', '精选'], ['all', '全部动态'], ['hot', '热点'], ['daily', '日报']] as const).map(([tab, label]) => <button key={tab} className={`pill${model.tab === tab ? ' on' : ''}`} aria-pressed={model.tab === tab} onClick={() => { model.setTab(tab); model.setLimit(50); }}>{label}</button>)}</div>
    <div className="news-domain-tabs" aria-label="资讯领域"><button className="text-action" aria-pressed={!model.domain} onClick={() => { model.setDomain(''); model.setLimit(50); }}>全部</button>{Object.entries(domainLabels).map(([domain, label]) => <button key={domain} className="text-action" aria-pressed={model.domain === domain} onClick={() => { model.setDomain(domain as keyof typeof domainLabels); model.setLimit(50); }}>{label}</button>)}</div>
    {model.tab === 'daily' ? <EditionPanel model={model} /> : <>
      <p className="meta">{events.length} 个{model.tab === 'hot' ? '多来源事件（本站订阅来源数，不代表全网热度或事实核验）' : '已整理事件'} · 待处理 {model.snapshot?.pending ?? '—'} 条</p>
      {!events.length ? <div className="foundation-empty"><h3>{model.tab === 'hot' ? '还没有多来源热点' : model.tab === 'featured' ? '还没有符合规则的精选' : '还没有已整理资讯'}</h3><p>采集和整理后显示真实结果；缺模型或失败的材料保留为待处理，旧刊仍可阅读。</p><div className="form-actions"><button className="text-action" onClick={() => { model.setTab('all'); model.setDomain(''); }}>查看全部动态</button><a className="foundation-link" href="#news/materials">查看待处理资料</a></div></div> : <ol className="news-materials">{visible.map(event => <li className="news-material" key={event.id}><div className="news-time-rail"><time dateTime={event.latestAt}>{formatNewsTime(event.latestAt)}</time><span>事件最新资料</span></div><article className="news-entry"><div className="news-entry-source"><span>{event.materials[0]?.sourceName} · {independentSources(event)} 个订阅来源</span><span className="news-status">{event.draft.domain && domainLabels[event.draft.domain]}</span></div><h3 className="news-entry-title"><a href={`#news/events/${event.id}`}>{event.draft.title}</a></h3><p className="news-summary">{event.draft.summary}</p><p className="news-reason">AI判断 · 推荐 {event.draft.score}/100：{event.draft.reason}</p>{event.materials.length > 1 && <details className="disclosure"><summary>{event.materials.length} 条相关报道 / 进展</summary><Related event={event} news={news} /></details>}<div className="news-tags">{event.draft.tags.map(tag => <span key={tag} className="news-status">{tag}</span>)}</div></article></li>)}</ol>}
      {visible.length < events.length && <button className="pill" onClick={() => model.setLimit(model.limit + 50)}>继续显示50个事件</button>}
    </>}
    <details className="disclosure news-run-disclosure"><summary>任务状态与失败重试</summary><NewsRuns model={model} /></details>
  </section>;
}
export function NewsEventPage({ id, model, news }: { id: string; model: EditorialController; news: NewsController }) {
  const event = model.snapshot?.events.find(e => e.id === id); const [original, setOriginal] = useState(false);
  if (!event) return <section className="news-page"><a href="#news" className="foundation-link">← 返回资讯</a><EditorialFeedback model={model} /><div className="foundation-empty"><h2>{model.loading ? '正在读取事件' : '未找到这个事件'}</h2><p>请重新读取核对；不会补写虚构内容。</p><button className="pill" onClick={() => void model.refresh()}>重新读取</button></div></section>;
  return <section className="news-page"><a className="foundation-link" href="#news">← 返回资讯（保留筛选）</a><EditorialFeedback model={model} /><div className="news-article-layout">
    <aside className="news-article-meta"><details open className="disclosure"><summary>来源与阅读目录</summary><p>{event.materials[0]?.sourceName} · {independentSources(event)} 个来源</p><p className="meta">资料最新时间：{formatNewsTime(event.latestAt)}</p><p className="meta">整理：{formatNewsTime(event.generatedAt)} · 事件 v{event.revision}</p><nav aria-label="文章目录">{[['guide', 'AI导读'], ['facts', '来源事实'], ['body', '可用摘要'], ['analysis', '事件分析'], ['sources', '相关报道与进展']].map(([target, label]) => <button key={target} className="text-action" onClick={() => document.getElementById(`news-${target}`)?.scrollIntoView({ behavior: 'smooth', block: 'start' })}>{label}</button>)}</nav></details></aside>
    <article className="news-article"><h2>{event.draft.title}</h2><section id="news-guide"><h3>AI导读</h3><p>{event.draft.summary}</p><p className="meta">模型 {event.model.provider} / {event.model.id} · 规则 v{event.configRevision} · 只依据已列订阅摘要</p></section><section id="news-facts"><h3>来源事实</h3><ul className="news-facts">{event.draft.facts.map((fact, i) => <Citations key={i} fact={fact} event={event} news={news} />)}</ul></section><section id="news-body"><h3>可用摘要</h3><div className="news-reading-tabs"><button className="pill" aria-pressed={!original} onClick={() => setOriginal(false)}>中文整理</button><button className="pill" aria-pressed={original} onClick={() => setOriginal(true)}>订阅原文</button></div><p className="meta">未取得许可正文，仅提供订阅摘要与原文链接；AI没有补写全文。</p>{original ? event.materials.map(m => <div className="news-original" key={m.id}><h4>{m.title}</h4><p className="meta">{m.sourceName} · 原发布时间：{publicationLabel(m)}</p><p>{m.summary || '订阅未提供摘要。'}{m.summaryTruncated && '（摘要节选）'}</p><SourceLink news={news} url={m.url}>打开来源原文 ↗</SourceLink></div>) : <><p>{event.draft.summary}</p><p className="meta">中文内容为AI依据摘要的整理，不是原文全文翻译。</p></>}</section><section id="news-analysis"><h3>事件分析 · AI判断</h3>{event.analysis ? <><ul className="news-facts">{event.analysis.judgments.map((fact, i) => <Citations key={i} fact={fact} event={event} news={news} />)}</ul><h4>未验证项与限制</h4><ul>{event.analysis.limitations.map((t, i) => <li key={i}>{t}</li>)}</ul><p className="meta">{formatNewsTime(event.analysis.generatedAt)} · {event.analysis.model.provider} / {event.analysis.model.id}</p></> : <p className="subtle">尚未分析。只分析本事件的工作影响，不自动修改项目或正式记录。</p>}<button className="pill" disabled={!!model.busy || model.active || !model.connected} onClick={() => void model.analyze(id, event.revision)}>{event.analysis ? '重新分析当前事件' : '分析这个事件'}</button></section><section id="news-sources"><h3>相关报道与进展</h3><Related event={event} news={news} /></section></article>
    <aside className="news-article-notes"><h3>推荐理由 · AI判断</h3><p className="news-reason">{event.draft.reason}</p><p className="meta">相关性 {event.draft.score}/100，不是可信概率。</p><h3>证据限制</h3><ul>{event.draft.limitations.map((t, i) => <li key={i}>{t}</li>)}</ul>{independentSources(event) === 1 && <p className="meta">只有一个订阅来源，不构成多方核验。</p>}<h3>主题标签</h3><div className="news-tags">{event.draft.tags.map(t => <span key={t} className="news-status">{t}</span>)}</div><h3>材料</h3><Related event={event} news={news} /></aside>
  </div></section>;
}
export function EditionPanel({ model }: { model: EditorialController }) {
  const editions = model.snapshot?.editions ?? []; const edition = editions.find(e => e.id === model.editionId) ?? editions[0];
  const [texts, setTexts] = useState<Record<string, string>>({}); const [failure, setFailure] = useState('');
  useEffect(() => { if (!edition || texts[edition.id] || !model.connected) return; let disposed = false; const id = edition.id; void invoke<string>('news_edition_text', { id }).then(text => { if (!disposed) { setTexts(p => ({ ...p, [id]: text })); setFailure(''); } }).catch(e => { if (!disposed) setFailure(workspaceError(e)); }); return () => { disposed = true; }; }, [edition?.id, model.connected, texts]);
  return <section className="news-edition"><div className="news-toolbar"><div><h2 className="title">固定日报</h2><p className="subtle">整期显示、复制与A4 PDF来自同一刊期，不受上方领域筛选影响。</p></div><button className="pill on" disabled={!model.connected || !!model.busy || model.active} onClick={() => void model.organize('daily')}>整理并生成新一期</button></div>
    {!edition ? <div className="foundation-empty"><h3>还没有固定刊期</h3><p>依据过去24小时的已整理内容成刊；空刊不凑数，失败不冒充成功。</p></div> : <><label className="news-edition-select">选择完整刊期<select className="select" value={edition.id} onChange={e => { model.setEditionId(e.target.value); model.setCopyText(''); }}>{editions.map(e => <option key={e.id} value={e.id}>{e.date} · v{e.version} · {formatNewsTime(e.generatedAt)}{e.incomplete ? '（覆盖不完整）' : ''}</option>)}</select></label><div className="form-actions"><button className="pill" disabled={!!model.busy || !model.connected} onClick={() => void model.copy(edition.id)}>复制整期</button><button className="pill" disabled={!!model.busy || !model.connected} onClick={() => void model.exportPdf(edition.id)}>导出A4 PDF</button></div>{failure && <p className="form-error" role="alert">{failure}</p>}<EditionDocument edition={edition} text={texts[edition.id]} />{model.copyText && <label>手选完整刊期<textarea className="input news-copy-text" readOnly value={model.copyText} onFocus={e => e.target.select()} /></label>}</>}
  </section>;
}
function EditionDocument({ edition, text }: { edition: Edition; text?: string }) { return <article className="news-edition-document" aria-label={`${edition.date} 日报 v${edition.version}`}>{text ? <pre>{text}</pre> : <p className="meta" role="status">正在读取完整刊期文本…</p>}</article>; }
