import { UILink } from './components/ui/ui-link.tsx';
import { Disclosure } from './components/ui/disclosure.tsx';
import { Button } from './components/ui/button.tsx';
import { NativeSelect } from './components/ui/native-select.tsx';
import { Input } from './components/ui/input.tsx';
import { Textarea } from './components/ui/textarea.tsx';
import { domainLabels } from './news-contract.ts';
import type { EditorialController } from './use-news-editorial.ts';
import { equalEditorial } from './news-editorial-contract.ts';
import { EditorialFeedback } from './news-reading-panels.tsx';
import type { PiModel } from './pi-contract.ts';
export function NewsPreferences({ model, models = [], section = 'domains' }: { model: EditorialController; models?: PiModel[]; section?: 'domains' | 'ai' | 'automation' }) {
  const title = { domains: '领域与筛选', ai: 'AI 处理', automation: '采集与日报' }[section];
  const draft = model.draft; const config = draft?.config;
  if (!draft || !config) return <section className="news-page"><h2 className="title">{title}</h2><EditorialFeedback model={model} /><Button variant="app-pill" className="pill" disabled={model.loading || !model.connected} onClick={() => void model.refresh()}>{model.loading ? '正在读取…' : '读取资讯配置'}</Button></section>;
  const dirty = !!model.snapshot && !equalEditorial(config, model.snapshot.preferences.config);
  const update = (patch: Partial<typeof config>) => model.changeConfig({ ...config, ...patch });
  return <section className="news-page"><div><h2 className="title">{title}</h2><p className="subtle">当前正式配置 v{model.snapshot?.preferences.revision} · {dirty ? '有未保存草稿' : '与正式配置一致'}。三个配置页共用草稿；保存会一并保存领域、AI和运行配置，下次任务生效。切页保留输入，旧刊不重写。</p></div><EditorialFeedback model={model} />
    <form className="news-source-form news-rules-form" onSubmit={e => { e.preventDefault(); void model.save(); }}>
      {section === 'automation' && <fieldset className="news-domain-fields"><legend>订阅网络</legend>
        <p className="meta">当前已保存：{model.snapshot?.preferences.config.collectionProxy != null ? '手动 HTTP 代理' : '直连'}。保存后用于下一次信源预览、采集和抓取失败重试；正在采集的任务沿用开始时的设置。</p>
        <label>采集连接方式<NativeSelect variant="app" className="select" value={config.collectionProxy == null ? 'direct' : 'proxy'} onChange={e => update({ collectionProxy: e.target.value === 'proxy' ? '' : null })}><option value="direct">直连</option><option value="proxy">手动 HTTP 代理</option></NativeSelect></label>
        {config.collectionProxy != null && <><label>代理地址<Input variant="app" className="input" type="url" required maxLength={512} value={config.collectionProxy} onChange={e => update({ collectionProxy: e.target.value })} placeholder="http://127.0.0.1:7890" autoComplete="off" spellCheck={false} /></label><p className="meta">填写代理软件的 HTTP 或 Mixed 地址，示例端口需要替换为实际端口。仅支持 http://，不支持 SOCKS 地址或需要登录的代理。代理软件需要保持运行，域名解析由所填代理负责。</p></>}
        <p className="meta">不自动读取系统代理。此设置仅用于 RSS / Atom 采集，AI 模型连接单独配置。保存后可回到信源管理，先预览或重试一个失败信源；旧错误记录会保留。</p>
        <UILink variant="text" className="foundation-link" href="#settings/news">前往信源管理 →</UILink>
      </fieldset>}
      {section === 'domains' && <fieldset className="news-domain-fields"><legend>领域与筛选</legend>{config.domains.map((r, i) => <section className="news-rule" key={r.domain}><label className="choice"><Input variant="inline" type="checkbox" checked={r.enabled} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, enabled: e.target.checked } : v) })} />{domainLabels[r.domain]}</label><label>范围与推荐规则<Textarea variant="inline" aria-label={`${domainLabels[r.domain]}范围与推荐规则`} className="input" required maxLength={2000} value={r.rule} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, rule: e.target.value } : v) })} /></label><div className="news-rule-numbers"><label>日报最低相关性<Input variant="app" className="input" type="number" min={0} max={100} required value={r.minScore} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, minScore: e.target.valueAsNumber } : v) })} /></label><label>该领域每期最多条数<Input variant="app" className="input" type="number" min={0} max={5} required value={r.dailyLimit} onChange={e => update({ domains: config.domains.map((v, n) => n === i ? { ...v, dailyLimit: e.target.valueAsNumber } : v) })} /></label></div></section>)}</fieldset>}
      {section === 'ai' && <fieldset className="news-domain-fields"><legend>AI处理</legend><p className="meta">模型与认证复用本应用的 <UILink variant="text" href="#settings/models" className="foundation-link">模型连接</UILink>。这里不填写Key；留空使用本应用可用默认模型，未配置时资料保持待处理。推荐分是工作价值判断，不是可信概率。</p><label>本应用已加载的模型<NativeSelect variant="app" aria-label="资讯模型" className="select" value={config.model ? JSON.stringify([config.model.provider, config.model.id]) : ''} onChange={e => { if (!e.target.value) update({ model: null }); else { const [provider, id] = JSON.parse(e.target.value) as [string, string]; update({ model: { provider, id } }); } }}><option value="">使用本应用可用默认模型</option>{config.model && !models.some(m => m.provider === config.model!.provider && m.id === config.model!.id) && <option value={JSON.stringify([config.model.provider, config.model.id])}>当前指定：{config.model.provider} / {config.model.id}（运行时核对）</option>}{models.map(m => <option key={JSON.stringify([m.provider, m.id])} value={JSON.stringify([m.provider, m.id])}>{m.name} · {m.provider}</option>)}</NativeSelect></label>{!models.length && <p className="meta">尚未加载模型列表；在Pi模型设置保存或连接后可选择。默认选项会在任务开始时核对实际可用模型。</p>}<Disclosure className="disclosure"><summary>高级：指定模型标识</summary><div className="news-rule-numbers"><label>模型提供商<Input variant="app" className="input" value={config.model?.provider ?? ''} maxLength={200} onChange={e => update({ model: { provider: e.target.value, id: config.model?.id ?? '' } })} /></label><label>模型ID<Input variant="app" className="input" value={config.model?.id ?? ''} maxLength={300} onChange={e => update({ model: { provider: config.model?.provider ?? '', id: e.target.value } })} /></label></div></Disclosure><div className="news-rule-numbers"><label>精选最低相关性<Input variant="app" className="input" type="number" min={0} max={100} required value={config.featuredScore} onChange={e => update({ featuredScore: e.target.valueAsNumber })} /></label><label>总览与首页最多条数<Input variant="app" className="input" type="number" min={0} max={3} required value={config.overviewLimit} onChange={e => update({ overviewLimit: e.target.valueAsNumber })} /></label></div><p className="meta">范围内未精选资讯仍能在全部动态查看；临界分、证据冲突或归组不明确时做一次复判，模型错误不盲重试。</p></fieldset>}
      {section === 'automation' && <fieldset className="news-domain-fields"><legend>采集与运行</legend><label className="choice"><Input variant="inline" type="checkbox" checked={config.autoCollect} onChange={e => update({ autoCollect: e.target.checked })} />按信源频率自动采集</label><label className="choice"><Input variant="inline" type="checkbox" checked={config.autoDaily} onChange={e => update({ autoDaily: e.target.checked })} />自动生成每日固定日报</label><label>日报时间（北京时间）<Input variant="app" className="input" type="time" required value={config.dailyTime} onChange={e => update({ dailyTime: e.target.value })} /></label><p className="meta">本应用实际运行时检查；当日时点后启动且未跑则补一次，不补多天。自动日报先采集再整理；暂停保留历史。关闭主窗口当前会退出，托盘运行等待后台模块接入。失败不自动再次调用付费模型，请在记录中手动重试。</p></fieldset>}
      {model.pending && <p className="warn-t">上次保存回执待核对，草稿仍保留。可核对结果或重发同一个请求，不创建重复配置版本。</p>}
      {draft.revision !== model.snapshot?.preferences.revision && <p className="warn-t">正式配置已有更新，草稿基于 v{draft.revision}。<Button variant="app-text" type="button" className="text-action" disabled={!!model.pending} onClick={model.rebase}>保留草稿并对照最新版本</Button></p>}
      <UILink variant="text" className="foundation-link" href="#jobs">查看后台任务与运行记录 →</UILink><div className="form-actions"><Button variant="app-pill" className="pill on" type="submit" disabled={!!model.busy || !model.connected}>{model.pending ? '重发上次保存请求' : '保存资讯配置'}</Button>{model.pending && <Button variant="app-pill" className="pill" type="button" disabled={!!model.busy} onClick={() => void model.reconcile()}>核对上次保存</Button>}</div>
    </form>
  </section>;
}
