import { useRef, useState } from 'react';
import type { ChangeEvent, FormEvent, KeyboardEvent } from 'react';
import type { PiController } from './use-pi.ts';
import { messageView, toolResultText } from './pi-messages.ts';
import { piError } from './pi-client.ts';
const labels:Record<string,string>={plain:'',streaming:'接收中',success:'消息已结束',error:'失败',interrupted:'已中断',incomplete:'未完整结束',none:'',starting:'正在接受请求',running:'工作中',stopping:'正在停止',compacting:'正在压缩上下文',idle:'空闲',finished:'已结束'};
function Message({value}:{value:unknown}){const m=messageView(value);return <article className={`pi-message ${m.role==='user'?'pi-user-message':''}`}><header><strong>{m.title}</strong>{m.status!=='plain'&&<span className="meta">{labels[m.status]??m.status}</span>}</header>{m.parts.map((part,index)=>part.kind==='thinking'||part.kind==='toolCall'?<details className="pi-tool" key={index}><summary>{part.title??(part.kind==='thinking'?'思考过程':'工具调用')}</summary><pre>{part.text}</pre></details>:<p key={index} className="pi-message-text">{part.text}</p>)}{m.error&&<p className="form-error">{m.error}</p>}</article>;}
function RuntimeInfo({model}:{model:PiController}){const s=model.snapshot;return <details className="pi-runtime"><summary>工作目录与原版 Pi</summary><dl><dt>版本</dt><dd>{s?.runtime?`Pi ${s.runtime.piVersion} · Node ${s.runtime.nodeVersion}`:'尚未启动'}</dd><dt>运行文件</dt><dd>{s?.runtime?.root??'使用本应用独立资源，不调用系统其他 Pi'}</dd><dt>工作目录</dt><dd>{s?.cwd??'默认本应用工作目录'}</dd><dt>资源与配置</dt><dd>{s?.paths?.agent??'数据根内 pi/agent'}</dd><dt>原生会话</dt><dd>{s?.paths?.sessions??'数据根内 pi/sessions'}</dd></dl><label className="pi-field">下次连接的工作目录（空白使用应用默认）<input value={model.cwd} onChange={e=>model.setCwd(e.target.value)} placeholder="可选绝对目录" spellCheck={false}/></label><p className="subtle">默认不加载外部项目资源，不改原版核心。独立目录不是文件权限沙箱；扩展与原生终端交接在 S04 接入。</p></details>;}
function Feedback({model}:{model:PiController}){return <>{(model.error??model.snapshot?.error?.message)&&<p className="form-error" role="alert">{model.error??model.snapshot?.error?.message}</p>}{model.notice&&<p role="status">{model.notice}</p>}{model.snapshot?.notice&&<p role="status">{model.snapshot.notice}</p>}</>;}
export function PiSettings({model}:{model:PiController}){
  const form=model.modelForm,[error,setError]=useState<string|null>(null),s=model.snapshot;
  const busy=!!model.action||!!s?.busy||!!s?.stopping;
  async function save(e:FormEvent){e.preventDefault();setError(null);const context=Number(form.contextWindow),max=Number(form.maxTokens);if(!/^\d+$/.test(form.contextWindow)||!/^\d+$/.test(form.maxTokens)||!Number.isSafeInteger(context)||context<=0||!Number.isSafeInteger(max)||max<=0){setError('上下文和最大输出需为正整数，输入仍保留。');return;}
    const sent={...form};if(await model.saveModel({...form,contextWindow:context,maxTokens:max,apiKey:form.apiKey||null}))model.setModelForm(current=>current.apiKey===sent.apiKey?{...current,apiKey:''}:current);
  }
  return <section className="foundation-section pi-settings" aria-labelledby="pi-settings-title"><h2 id="pi-settings-title">模型连接</h2><p className="subtle">只保存到本应用。使用原版 Pi 的模型与认证机制，不读取其他 Pi 的密钥。</p>
    {!model.root?<p>请先选择数据目录，再保存模型设置。</p>:<form className="pi-model-form" onSubmit={e=>void save(e)}>
      <div className="pi-fields"><label className="pi-field">服务标识<input required maxLength={80} value={form.provider} onChange={e=>model.setModelForm({...form,provider:e.target.value})} placeholder="例如 my-provider" spellCheck={false}/></label><label className="pi-field">原生 API 类型<select value={form.api} onChange={e=>model.setModelForm({...form,api:e.target.value})}><option value="openai-completions">OpenAI Chat Completions</option><option value="openai-responses">OpenAI Responses</option><option value="anthropic-messages">Anthropic Messages</option><option value="google-generative-ai">Google Generative AI</option></select></label></div>
      <label className="pi-field">API 地址<input required value={form.baseUrl} onChange={e=>model.setModelForm({...form,baseUrl:e.target.value})} placeholder="https://…" spellCheck={false}/></label>
      <div className="pi-fields"><label className="pi-field">模型 ID<input required value={form.modelId} onChange={e=>model.setModelForm({...form,modelId:e.target.value})} spellCheck={false}/></label><label className="pi-field">显示名称<input required value={form.name} onChange={e=>model.setModelForm({...form,name:e.target.value})}/></label></div>
      <div className="pi-fields"><label className="pi-field">上下文长度<input inputMode="numeric" value={form.contextWindow} onChange={e=>model.setModelForm({...form,contextWindow:e.target.value})}/></label><label className="pi-field">最大输出长度<input inputMode="numeric" value={form.maxTokens} onChange={e=>model.setModelForm({...form,maxTokens:e.target.value})}/></label></div>
      <div className="pi-actions"><label className="pi-check"><input type="checkbox" checked={form.reasoning} onChange={e=>model.setModelForm({...form,reasoning:e.target.checked})}/>声明支持思考</label><label className="pi-check"><input type="checkbox" checked={form.supportsImages} onChange={e=>model.setModelForm({...form,supportsImages:e.target.checked})}/>声明支持图片</label></div>
      <label className="pi-field">API Key<input type="password" autoComplete="off" value={form.apiKey} onChange={e=>model.setModelForm({...form,apiKey:e.target.value})} placeholder="留空保留此服务原有认证" spellCheck={false}/></label><p className="meta">不回显已有密钥。服务不要求认证时，请按服务说明填写它接受的值；不自动编造 Key。关闭额外缓存保活与自动重试。</p>
      {error&&<p className="form-error" role="alert">{error}</p>}<button className="pill on" disabled={busy||!model.connected}>保存并由原版加载</button>
    </form>}
    <Feedback model={model}/><div className="pi-actions"><button className="pill" onClick={()=>void model.connect()} disabled={busy||!model.root||!model.connected}>连接 / 重新读取</button>{s?.connection==='ready'&&<a className="foundation-link" href="#agent">打开 Agent</a>}</div>
    <p className="subtle">{s?.connection==='ready'?`原版已加载 ${s.models.length} 个可用模型；列入清单不等于端点已通过真实回复验证。`:s?.connection==='connecting'?'正在启动本应用原版 Pi…':'尚未连接。保存失败时表单保留，不自动调用模型。'}</p>
    <RuntimeInfo model={model}/>
  </section>;
}
export function AgentPanel({model}:{model:PiController}){
  const s=model.snapshot,state=s?.state,projection=s?.projection,modelValue=state?.model;
  const [attachmentError,setAttachmentError]=useState<string|null>(null),[attaching,setAttaching]=useState(false);
  const composing=useRef(false),fileInput=useRef<HTMLInputElement>(null);
  const ready=s?.connection==='ready',busy=!!model.action||!!s?.busy||!!s?.stopping;
  const running=!!projection&&projection.activity!=='idle';
  const available=!!modelValue&&!!s?.models.some(m=>m.provider===modelValue.provider&&m.id===modelValue.id);
  const imageUnsupported=model.draft.images.length>0&&!modelValue?.input.includes('image');
  const sendDisabled=!ready||!available||busy||attaching||imageUnsupported||(!model.draft.text.trim()&&!model.draft.images.length);
  async function attach(event:ChangeEvent<HTMLInputElement>){const files=Array.from(event.target.files??[]);event.target.value='';if(!files.length)return;setAttachmentError(null);setAttaching(true);
    try{if(files.length+model.draft.images.length>4)throw new Error('最多附加4张图片，原附件仍保留。');const key=model.draftKey,existing=[...model.draft.images];const loaded=await Promise.all(files.map(async file=>{if(!['image/png','image/jpeg','image/webp','image/gif'].includes(file.type)||file.size>3*1024*1024)throw new Error('请选择 PNG、JPEG、WebP 或 GIF，每张不超过3MiB。');const data=await new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onerror=()=>reject(new Error('图片读取失败，文字和原附件仍保留。'));reader.onload=()=>resolve(String(reader.result).split(',')[1]??'');reader.readAsDataURL(file);});return{id:crypto.randomUUID(),name:file.name,mimeType:file.type,data};}));if([...existing,...loaded].reduce((n,i)=>n+i.data.length,0)>8*1024*1024)throw new Error('图片合计编码超过8MiB，原附件仍保留。');model.setImages([...existing,...loaded],key);}catch(e){setAttachmentError(piError(e));}finally{setAttaching(false);}
  }
  function keydown(event:KeyboardEvent<HTMLTextAreaElement>){if(event.key==='Enter'&&!event.shiftKey&&!composing.current&&!event.nativeEvent.isComposing&&event.keyCode!==229){event.preventDefault();if(!sendDisabled)void model.send(running?'followUp':null);}}
  return <div className="pi-agent-layout">
    <details className="pi-sessions" open><summary>会话</summary><div className="pi-actions"><button className="pill" disabled={!ready||busy||running} onClick={()=>void model.sessionAction('pi_new_session')}>新会话</button><button className="pill" onClick={()=>void model.reloadSessions()} disabled={!model.root}>刷新列表</button></div>
      {model.sessionError&&<p className="form-error" role="alert">{model.sessionError}</p>}{model.unreadable>0&&<p role="status">{model.unreadable} 个会话文件未能读取；原文件保留。</p>}
      <div className="pi-session-items">{!model.sessions.length?<p className="subtle">暂无已落盘会话。原版空会话尚未写入文件，不会补造历史。</p>:model.sessions.map(session=><button className="pi-session-item" key={session.path} aria-current={state?.sessionFile===session.path?'true':undefined} disabled={busy||running} onClick={()=>void (ready&&s?.cwd===session.cwd?model.sessionAction('pi_switch_session',{path:session.path}):model.connect(session))}><strong>{session.name??'未命名会话'}</strong><span className="meta">{session.updatedAt} · {session.messageCount} 条消息</span></button>)}</div>
    </details>
    <section className="pi-chat" aria-label="通用 Agent 对话"><header className="pi-chat-heading"><div><h2>{state?.sessionName??'新会话'}</h2><p className="subtle">{s?.connection==='connecting'?'正在连接原版 Pi…':ready?available?`${modelValue?.name} · ${labels[projection?.activity??'idle']??projection?.activity}`:'原版已就绪 · 请先配置模型':s?.connection==='error'?'连接中断，可重新连接':'尚未连接原版 Pi'}</p></div><div className="pi-actions"><button className="pill" disabled={busy||running||!model.root||!model.connected} onClick={()=>void model.connect()}>连接 / 重连</button>{ready&&<button className="pill" disabled={busy} onClick={()=>void model.disconnect()}>断开</button>}</div></header>
      {ready&&s.models.length>0&&<label className="pi-field pi-model-choice">当前模型<select value={modelValue?JSON.stringify([modelValue.provider,modelValue.id]):''} disabled={busy||running} onChange={e=>{const [provider,id]=JSON.parse(e.target.value) as [string,string];void model.sessionAction('pi_select_model',{provider,id});}}>{!available&&<option value="">请选择模型</option>}{s.models.map(m=><option key={JSON.stringify([m.provider,m.id])} value={JSON.stringify([m.provider,m.id])}>{m.name} · {m.provider}</option>)}</select></label>}
      <details><summary>会话名称</summary><form className="pi-actions" onSubmit={e=>{e.preventDefault();void model.sessionAction('pi_name_session',{name:model.sessionName});}}><label className="pi-field">新名称<input value={model.sessionName} maxLength={1000} onChange={e=>model.setSessionName(e.target.value)}/></label><button className="pill" disabled={!ready||busy||running||!model.sessionName.trim()}>保存名称</button></form></details>
      <Feedback model={model}/>{projection?.notice&&<p role="status">{projection.notice}</p>}{projection?.outcome&&projection.outcome!=='none'&&<p className="pi-outcome" role="status">本轮：{projection.outcome==='success'?'实际回复已完成':labels[projection.outcome]??projection.outcome}</p>}
      <div className="pi-chat-messages" aria-label="会话消息">{!projection?.messages.length&&!projection?.partial?<div className="pi-chat-empty"><h3>{available?'可以开始新的对话':'先连接你自己的模型'}</h3><p>{available?'输入自由任务，保留原版 Pi 的工具与会话能力。':'输入可先写在下面，切页不会丢；未配置时不会发送或生成假回复。'}</p>{!available&&<a className="foundation-link" href="#settings">前往模型设置</a>}</div>:projection?.messages.map((message,index)=><Message key={index} value={message}/>)}{projection?.partial!=null&&<Message value={projection.partial}/>} </div>
      {!!projection?.tools.length&&<section className="pi-tools" aria-label="工具过程"><h3>工具过程</h3>{projection.tools.map(t=><details className="pi-tool" key={t.id} open={t.status==='error'}><summary>{t.name} · {labels[t.status]??t.status}</summary><h4>输入</h4><pre>{JSON.stringify(t.args??{},null,2)}</pre><h4>输出</h4><pre>{toolResultText(t.result)}</pre></details>)}</section>}
      {!!s?.recoveredQueue.length&&<details open><summary>停止时保留的排队文字</summary>{s.recoveredQueue.map((text,index)=><div className="pi-queue" key={index}><p>{text}</p><button className="pill" onClick={()=>model.recoverQueue(index)}>取回输入</button></div>)}</details>}
      {!!model.acceptedInputs.length&&<details><summary>本次打开期间最近20次已接受输入（可取回）</summary><p className="meta">每会话只保留最近20次在本次应用内存中，不自动重发；已接受不等于已执行。原生会话仍是历史记录。</p>{model.acceptedInputs.map(item=><div className="pi-queue" key={item.id}><p>{item.draft.text}</p>{item.draft.images.map(image=><p className="meta" key={image.id}>{image.name}</p>)}<button className="pill" type="button" onClick={()=>model.recoverAccepted(item.id)}>取回此输入</button></div>)}</details>}
      <form className="pi-composer" onSubmit={e=>{e.preventDefault();if(!sendDisabled)void model.send(running?'followUp':null);}}><label className="pi-field">消息<textarea aria-label="消息" value={model.draft.text} onChange={e=>model.setText(e.target.value)} onKeyDown={keydown} onCompositionStart={()=>{composing.current=true;}} onCompositionEnd={()=>{composing.current=false;}} maxLength={100000} placeholder="输入自由任务或原生 Skill 命令…"/></label>
        {model.draft.images.map(image=><div className="pi-attachment" key={image.id}><span>{image.name}</span><button className="pill" type="button" disabled={attaching} onClick={()=>model.setImages(model.draft.images.filter(v=>v.id!==image.id))}>移除图片</button></div>)}
        {attachmentError&&<p className="form-error" role="alert">{attachmentError}</p>}{imageUnsupported&&<p className="form-error" role="alert">当前模型不支持图片，附件仍保留；请换模型或移除图片后发送。</p>}
        <div className="pi-actions"><input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp,image/gif" multiple hidden onChange={e=>void attach(e)}/><button className="pill" type="button" disabled={attaching} onClick={()=>fileInput.current?.click()}>{attaching?'读取图片…':'附加图片'}</button><span className="meta">Enter 发送 · Shift+Enter 换行</span><button className="pill on" disabled={sendDisabled}>{running?'排在之后':'发送'}</button>{running&&<button className="pill" type="button" disabled={sendDisabled} onClick={()=>void model.send('steer')}>插入当前任务</button>}<button className="pill" type="button" disabled={!model.connected||!s||s.stopping||!ready&&s.connection!=='connecting'} onClick={()=>void model.stop()}>{s?.stopping?'正在停止…':'停止'}</button></div>
      </form><RuntimeInfo model={model}/>
    </section>
  </div>;
}
