// Only an exact stable main build may produce the public Windows update feed.
import fs from 'node:fs';
import path from 'node:path';
import { createHash } from 'node:crypto';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const readJson=file=>JSON.parse(fs.readFileSync(path.join(root,file),'utf8'));
const config=readJson('app/src-tauri/tauri.conf.json');
const version=config.version,tag=process.env.RELEASE_TAG;
if(!/^\d+\.\d+\.\d+$/.test(version)||tag!==`v${version}`)throw Error('Stable release version mismatch');
for(const file of ['package.json','app/package.json','app/package-lock.json'])if(readJson(file).version!==version)throw Error(`Version mismatch: ${file}`);
if(!fs.readFileSync(path.join(root,'app/src-tauri/Cargo.toml'),'utf8').includes(`version = "${version}"`))throw Error('Rust version mismatch');
if(config.identifier!=='com.azcine.workbench.release'||config.app.appDirectoriesOverride||config.plugins.updater.dangerousInsecureTransportProtocol||config.plugins.updater.endpoints.length!==1||config.plugins.updater.endpoints[0]!=='https://github.com/azcine94/_AZCine/releases/latest/download/latest.json')throw Error('Validation configuration cannot be released');
if(process.env.GITHUB_REPOSITORY!=='azcine94/_AZCine')throw Error('Unexpected release repository');
const target=process.env.CARGO_TARGET_DIR;if(!target)throw Error('Explicit release target required');
const name=`AZCine_${version}_x64-setup.exe`,setup=path.join(target,'release/bundle/nsis',name);
const signature=fs.readFileSync(setup+'.sig','utf8').trim();if(!signature||fs.statSync(setup).size<1_000_000)throw Error('Missing signed installer');
const readme=fs.readFileSync(path.join(root,'README.md'),'utf8');
const versionNotes=path.join(root,'.github/release-notes',`${version}.md`);
const notes=fs.existsSync(versionNotes)?fs.readFileSync(versionNotes,'utf8').trim():readme.split(`<!-- release-notes:${version} -->`)[1]?.split('<!-- release-notes:end -->')[0]?.trim();
if(!notes)throw Error('Missing reviewed release notes');
const out=path.join(root,'artifacts/release');fs.mkdirSync(out,{recursive:true});
for(const file of [name,name+'.sig'])fs.copyFileSync(path.join(path.dirname(setup),file),path.join(out,file),fs.constants.COPYFILE_EXCL);
const feed={version,notes,pub_date:new Date().toISOString(),platforms:{'windows-x86_64':{signature,url:`https://github.com/azcine94/_AZCine/releases/download/${tag}/${name}`}}};
fs.writeFileSync(path.join(out,'latest.json'),JSON.stringify(feed,null,2)+'\n',{flag:'wx'});
const files=[name,name+'.sig','latest.json'];
const sums=files.map(file=>`${createHash('sha256').update(fs.readFileSync(path.join(out,file))).digest('hex')}  ${file}`).join('\n')+'\n';
fs.writeFileSync(path.join(out,'SHA256SUMS.txt'),sums,{flag:'wx'});
fs.writeFileSync(path.join(out,'release-notes.md'),notes+`\n\nSource: \`${process.env.GITHUB_SHA}\`\n`,{flag:'wx'});
console.log(`Prepared ${tag}: Windows x64 NSIS, updater signature, latest.json, SHA256SUMS.txt`);
